{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7d26d8bf",
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "execution": {
     "iopub.execute_input": "2025-05-02T10:50:12.163011Z",
     "iopub.status.busy": "2025-05-02T10:50:12.162580Z",
     "iopub.status.idle": "2025-05-02T10:50:12.200345Z",
     "shell.execute_reply": "2025-05-02T10:50:12.199335Z"
    },
    "papermill": {
     "duration": 0.043898,
     "end_time": "2025-05-02T10:50:12.202078",
     "exception": false,
     "start_time": "2025-05-02T10:50:12.158180",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "## Corrosion Global Terms\n",
    "#===============================================\n",
    "# 1. Common metal ions to look for Types of metal ions and compounds\n",
    "metal_terms = {\n",
    "    'iron': ['Fe2+', 'Fe3+', 'iron', 'ferrous', 'ferric', 'heme', 'iron-sulfur', 'rust', 'ochre', 'iron oxide', 'iron precipitation', 'siderophore', 'ferritin'],\n",
    "    'manganese': ['Mn2+', 'manganese', 'mn', 'manganous', 'manganic', 'manganese oxidation', 'manganese oxide', 'MnO2'],\n",
    "    'copper': ['Cu+', 'Cu2+', 'copper', 'cupric', 'cuprous', 'copper oxide', 'copper corrosion'],\n",
    "    'nickel': ['Ni2+', 'nickel', 'nickelous', 'nickel oxidation', 'nickel reduction'],\n",
    "    'cobalt': ['Co2+', 'cobalt', 'cobaltous', 'cobalamin', 'vitamin B12'],\n",
    "    'magnesium': ['Mg2+', 'magnesium', 'magnesium oxide'],\n",
    "    'calcium': ['Ca2+', 'calcium', 'calcium carbonate', 'calcite', 'calcium precipitation'],\n",
    "    'Mo': ['Mo', 'molybdenum', 'molybdopterin', 'molybdenum cofactor'],\n",
    "    'V5+': ['V5+', 'vanadium', 'vanadate', 'vanadyl'],\n",
    "    'Al3+': ['Al3+', 'aluminum', 'aluminate', 'aluminum oxide'],\n",
    "    'Cr3+': ['Cr3+', 'chromium', 'chromate', 'dichromate', 'chromium oxide'],\n",
    "    'zinc': ['Zn2+', 'zinc', 'zinc finger', 'zinc oxide'],\n",
    "    'sodium': ['Na+', 'sodium', 'NaCl', 'sodium transport', 'sodium gradient'],\n",
    "    'potassium': ['K+', 'potassium', 'KCl', 'potassium transport', 'potassium channel'],\n",
    "    'selenium': ['selenium', 'Se', 'selenocysteine', 'selenoprotein', 'selenite'],\n",
    "    'barium': ['Ba2+', 'barium', 'barium sulfate', 'barite'],\n",
    "    'phosphate': ['HPO4-2', 'PO4-3', 'phosphate', 'phosphates'],\n",
    "    'nitrate': ['NO3-', 'nitrate', 'nitrates'],\n",
    "    'nitrite': ['NO2-', 'nitrite', 'nitrites'],\n",
    "    'chloride': ['Cl-', 'chloride', 'chlorine'],\n",
    "    'sulfate': ['SO4-2', 'sulfate', 'sulfates'],\n",
    "    'sulfide': ['S', 'sulfide', 'sulfides', 'H2S', 'hydrogen sulfide'],\n",
    "    'thiosulfate': ['S2O3-2', 'thiosulfate'],\n",
    "    'oxygen': ['O2', 'oxygen', 'oxidase'],\n",
    "    'hydrogen': ['H2', 'hydrogen', 'hydrogenase', 'hydrogen uptake', 'hydrogen evolution'],\n",
    "    'organics': ['methane', 'CH4', 'methane', 'methanogenic', 'methanogenesis', 'formate','formate', 'formic acid', 'HCOO-', 'acetate', 'acetate', 'acetic acid', 'CH3COO-', \n",
    "                    'propionate','propionate', 'propionic acid', 'butyrate','butyrate', 'butyric acid','lactate', 'lactic acid', 'mercaptans', 'mercaptan', 'thiol', 'methanethiol',\n",
    "                    'ethanethiol', 'H2S', 'alcohol', 'ethanol', 'methanol', 'propanol', 'alcohol']\n",
    "}\n",
    "# 2. Comprehensive corrosion mechanisms classification Specific biochemical processes causing corrosion\n",
    "corrosion_mechanisms = {\n",
    "    'direct_eet': ['cytochrome', 'electron transfer', 'conductive pili', 'nanowire', 'mtrABC', 'omcS', 'oxidoreductase', 'redox', 'reductase', 'oxidase', 'electron conduit', \n",
    "                    'direct electron transfer'],\n",
    "    'indirect_eet': ['shuttle', 'mediator', 'redox mediator', 'electron shuttle', 'flavin', 'quinone', 'humic substance'],\n",
    "    'acid_production': ['acid', 'acidification', 'fermentation', 'lactic acid', 'formic acid', 'acetic acid', 'oxalic acid', 'organic acid', 'acetate production', 'lactate metabolism', \n",
    "                        'formate production', 'proton generation', 'low pH'],\n",
    "    'h2_consumption': ['hydrogenase', 'hydrogen uptake', 'hydrogen consumption', 'h2', 'H2 oxidation', 'H2ase', 'hydrogen metabolism'],\n",
    "    'o2_consumption': ['oxidase', 'oxygen reduction', 'aerobic respiration', 'oxygen reduc', 'oxygen consum',  'oxygen scavenging', 'oxygen stress', 'oxidative phosphorylation'],\n",
    "    'biofilm_formation': ['polysaccharide', 'adhesin', 'biofilm', 'EPS', 'extracellular polymeric substance', 'curli', 'exopolymer', 'extracellular matrix', 'adhesion', 'colonization', \n",
    "                            'attachment', 'surface', \n",
    "    'adherence', 'biofilm maturation'],\n",
    "    'sulfur_metabolism': ['sulfate reduc', 'sulfide', 'sulfite', 'thiosulfate', 'sulfur oxidation', 'SRB',     'sulfur disproportionation', 'sulfate-reducing bacteria', 'sulfur respiration'],\n",
    "    'metal_transformation': ['iron reduction', 'manganese oxidation', 'metal oxide', 'ochre formation',  'iron oxide deposits', 'iron precipitation', 'rust formation', 'metal deposition',    \n",
    "                                'metal solubilization', 'mineral dissolution', 'mineral precipitation'],\n",
    "    'iron_metabolism': ['iron reduc', 'ferric reduc', 'iron oxid', 'ferrous oxid', 'iron uptake', 'iron transport', 'iron storage', 'iron homeostasis', 'siderophore production'],\n",
    "    'metal_chelation': ['siderophore', 'metal binding', 'chelator', 'metallophore', 'iron complex',   'metal transport', 'chelation', 'metal complexation', 'metal sequestration'],\n",
    "    'carbon_metabolism': ['carbon fixation', 'carbon utilization', 'carbohydrate metabolism', 'glycolysis',   'TCA cycle', 'carbon flux', 'carbon assimilation'],\n",
    "    'ph_modulation': ['acid tolerance', 'alkaline tolerance', 'proton pump', 'pH homeostasis', 'pH stress',  'pH regulation', 'acid resistance']\n",
    "}\n",
    "\n",
    "# 3. Pathway categories Metabolic pathways relevant to corrosion\n",
    "pathway_categories = {\n",
    "    'hydrogen_metabolism': [\n",
    "        'h2_consumption', 'hydrogenase', 'hydrogen uptake', 'hydrogen consumption', \n",
    "        'h2', 'H2 oxidation', 'H2ase', 'hydrogen production',\n",
    "        'FeFe-hydrogenase', 'NiFe-hydrogenase', 'hydrogen evolution',\n",
    "        'hydrogen cycling', 'H2 sensing', 'proton reduction'\n",
    "    ],\n",
    "    'oxygen_metabolism': [\n",
    "        'o2_consumption', 'aerobic_respiration', 'oxygen reduction', \n",
    "        'oxygen consumption', 'cytochrome oxidase', 'terminal oxidase',\n",
    "        'oxygen reductase', 'superoxide dismutase', 'catalase',\n",
    "        'oxidative stress', 'oxygen sensor', 'oxygen tolerance'\n",
    "    ],\n",
    "    'nitrogen_metabolism': [\n",
    "        'denitrification', 'nitrate_reduction', 'nitrite_reduction',\n",
    "        'nitrogen metabolism', 'nitrate', 'nitrite',\n",
    "        'ammonia oxidation', 'nitrification', 'nitrogen fixation',\n",
    "        'ammonification', 'nitrous oxide reduction', 'nitric oxide reduction',\n",
    "        'dissimilatory nitrate reduction', 'nitrite reductase', 'nitrate reductase'\n",
    "    ],\n",
    "    'manganese_processes': [\n",
    "        'manganese_reduction', 'mn_redox', 'manganese oxidation',\n",
    "        'manganese oxide', 'pyrolusite', 'birnessite',\n",
    "        'manganese cycling', 'manganese mineral', 'manganese transport'\n",
    "    ], \n",
    "        'iron_sulfur_redox': [\n",
    "        'iron metabolism', 'sulfur metabolism', 'iron oxidation', 'iron reduction', \n",
    "        'iron reduc', 'ferric reduc', 'sulfate reduc', 'sulfide', 'sulfite', \n",
    "        'thiosulfate', 'sulfur oxidation', 'SRB',\n",
    "        'Fe-S cluster', 'iron-sulfur cluster', 'ferredoxin',\n",
    "        'rubredoxin', 'ferritin', 'bacterioferritin'\n",
    "    ],\n",
    "    'ocre_formation': [\n",
    "        'ocre', 'iron_oxide', 'iron_deposit', 'metal oxide', 'ochre formation', \n",
    "        'iron oxide deposits', 'iron precipitation', 'rust formation',\n",
    "        'ferrihydrite', 'goethite', 'magnetite', 'hematite',\n",
    "        'mineral precipitation', 'iron mineral'\n",
    "    ],\n",
    "    'sulfur_metabolism': [\n",
    "        'sulfur', 'sulfate', 'sulfide', 'thiosulfate', 'sulfite', 'sulfonate',\n",
    "        'sulfate reduction', 'sulfur oxidation', 'sulfur respiration',\n",
    "        'SRB', 'dsrAB', 'APS reductase', 'sulfide:quinone oxidoreductase',\n",
    "        'sulfur disproportionation', 'dissimilatory sulfate reduction'\n",
    "    ],\n",
    "    'electron_transfer': [\n",
    "        'cytochrome', 'electron transport', 'oxidoreductase', 'redox',\n",
    "        'electron transfer', 'direct EET', 'indirect EET', 'nanowire',\n",
    "        'conductive pili', 'electron shuttle', 'mtrABC', 'omcS',\n",
    "        'c-type cytochrome', 'multi-heme cytochrome', 'flavin'\n",
    "    ],\n",
    "    'organic_acid_metabolism': [\n",
    "        'acetate', 'acetic acid', 'acetyl', 'acetate metabolism', 'acetate production',\n",
    "        'oxalate', 'oxalic acid', 'oxalate metabolism', 'oxalate production',\n",
    "        'organic acid', 'fatty acid', 'butyric acid', 'butyrate', 'propionate', 'propionic acid',\n",
    "        'carboxylic acid', 'lactate', 'lactic acid', 'formate', 'formic acid',\n",
    "        'citrate', 'citric acid', 'succinate', 'succinic acid', 'fumarate', 'fumaric acid',\n",
    "        'malate', 'malic acid', 'pyruvate', 'pyruvic acid'\n",
    "    ],\n",
    "    'metal_organic_interaction': [\n",
    "        'siderophore', 'metal binding', 'metal chelation', 'iron chelation',\n",
    "        'iron complex', 'metal transport', 'metallophore', 'metal organic',\n",
    "        'organometallic', 'iron uptake', 'metal uptake', 'metalloprotein',\n",
    "        'iron-sulfur cluster', 'metal coordination', 'metal sequestration',\n",
    "        'ferric reductase', 'ferrous oxidase', 'metal homeostasis'\n",
    "    ],\n",
    "    'biofilm_formation': [\n",
    "        'biofilm', 'exopolysaccharide', 'EPS production', 'extracellular matrix',\n",
    "        'adhesion', 'attachment', 'colonization', 'surface attachment',\n",
    "        'polysaccharide biosynthesis', 'extracellular polymeric substance',\n",
    "        'cell aggregation', 'quorum sensing', 'biofilm maturation',\n",
    "        'biofilm regulation', 'biofilm dispersion', 'cell-cell adhesion',\n",
    "        'matrix production', 'pellicle', 'floc formation'\n",
    "    ],\n",
    "    'carbon_metabolism': [\n",
    "        'carbon fixation', 'carbon utilization', 'carbohydrate metabolism',\n",
    "        'glycolysis', 'TCA cycle', 'pentose phosphate pathway',\n",
    "        'gluconeogenesis', 'carbon assimilation', 'carbon flux',\n",
    "        'Calvin cycle', 'reductive acetyl-CoA pathway', 'carbon monoxide dehydrogenase'\n",
    "    ],\n",
    "    'ph_modulation': [\n",
    "        'acid', 'alkaline', 'proton pump', 'pH homeostasis',\n",
    "        'pH stress', 'acid tolerance', 'alkaline tolerance',\n",
    "        'proton motive force', 'pH regulation', 'acidic environment',\n",
    "        'alkaline environment', 'acid resistance', 'proton antiporter'\n",
    "    ],\n",
    "    'temp_response': [\n",
    "        'heat shock', 'cold shock', 'temperature response',\n",
    "        'thermophilic', 'psychrophilic', 'mesophilic',\n",
    "        'thermal adaptation', 'temperature stress', 'heat stress protein',\n",
    "        'cold stress protein', 'thermal stability', 'thermotolerance'\n",
    "    ],\n",
    "    'halogen_related': [\n",
    "        'halogen', 'chloride', 'bromide', 'iodide', 'fluoride',\n",
    "        'halide', 'dehalogenation', 'haloperoxidase', 'haloacid',\n",
    "        'chlorination', 'bromination', 'halomethane', 'haloalkane',\n",
    "        'organohalide', 'halotolerance', 'salt tolerance',\n",
    "        'halophilic', 'chloride transport', 'halide channel'\n",
    "    ],\n",
    "    'methanogenesis': [\n",
    "        'methanogenesis', 'methanobacterium', 'archaea', 'methane production',\n",
    "        'methyl-coenzyme M reductase', 'methanogenic', 'coenzyme F420',\n",
    "        'methyl-H4MPT', 'CO2 reduction', 'acetoclastic methanogenesis'\n",
    "    ],\n",
    "} \n",
    "# 4. Define organic matter categories - Types of processes organisms perform on organic matter\n",
    "organic_categories = {\n",
    "    'degradation': ['degradation', 'breakdown', 'catabolism', 'hydrolysis', 'digestion',\n",
    "                    'decomposition', 'mineralization', 'dissolution'],\n",
    "    'synthesis': ['biosynthesis', 'anabolism', 'synthesis', 'polymerization', 'assembly',\n",
    "                    'construction', 'formation', 'production'],\n",
    "    'transport': ['transport', 'uptake', 'export', 'secretion', 'efflux', 'influx',\n",
    "                    'extrusion', 'import', 'transmembrane transport', 'translocation'],\n",
    "    'modification': ['modification', 'conversion', 'transformation', 'transmutation',\n",
    "                    'alteration', 'rearrangement', 'isomerization', 'conjugation'],\n",
    "    'respiration': ['respiration', 'electron transport chain', 'oxidative phosphorylation',\n",
    "                    'terminal electron acceptor', 'cytochrome'],\n",
    "    'fermentation': ['fermentation', 'anaerobic metabolism', 'mixed acid fermentation',\n",
    "                    'alcohol fermentation', 'lactic acid fermentation'],\n",
    "    'oxidation': ['oxidation', 'oxidase', 'oxidoreductase', 'dehydrogenase',\n",
    "                    'hydroxylation', 'oxygenase'],\n",
    "    'reduction': ['reduction', 'reductase', 'hydrogenase', 'dehydrogenase',\n",
    "                    'nitrate reduction', 'sulfate reduction']\n",
    "}\n",
    "# 5. Corrosion-specific metal combinations\n",
    "corrosion_synergies = {\n",
    "    'Fe-S': ['iron sulfur', 'Fe-S', 'iron sulfide', 'FeS', 'Fe-S cluster'],\n",
    "    'Fe-Cl': ['iron chloride', 'FeCl', 'iron halide', 'ferric chloride'],\n",
    "    'Fe-C': ['iron carbon', 'FeC', 'iron carbonate', 'siderite'],\n",
    "    'Cu-Fe': ['copper iron', 'Cu-Fe', 'bimetallic', 'galvanic couple'],\n",
    "    'Mn-Fe': ['manganese iron', 'Mn-Fe', 'iron manganese oxide']\n",
    "}\n",
    "    \n",
    "# 6. FUNCTIONAL CATEGORIES - \n",
    "functional_categories = {\n",
    "    'iron/sulfur_redox': {'terms': ['iron_metabolism', 'sulfur_metabolism', 'iron_oxidation', 'iron_reduction',  'iron reduc', 'ferric reduc', 'sulfate reduc', 'sulfide', 'sulfite', \n",
    "                                    'thiosulfate', 'sulfur oxidation', 'SRB'],'score': 1.5},\n",
    "    'ocre': {'terms': ['ocre', 'iron_oxide', 'iron_deposit', 'metal oxide', 'ochre formation', 'iron oxide deposits', 'iron precipitation', 'rust formation'],'score': 1.5},   \n",
    "    'acid_production': {'terms': ['acid', 'acidification', 'fermentation', 'lactic acid', 'formic acid', 'acetic acid', 'oxalic acid', 'organic acid', 'acetate production', \n",
    "                                    'lactate metabolism', 'formate production'],'score': 1.5},\n",
    "    'electron transfer & redox': {'terms': ['direct_eet', 'redox', 'electron_transfer', 'omc', 'deet',  'cytochrome', 'electron transfer', 'conductive pili', 'nanowire', \n",
    "                                            'mtrABC', 'omcS', 'oxidoreductase', 'redox', 'reductase', 'oxidase'],'score': 1.1},\n",
    "    'biofilm_formation': {'terms': ['biofilm_formation', 'metal_chelation', 'quorum_sensing',  'extracellular_matrix', 'EPS', 'surface_disruption', 'polysaccharide', 'adhesin', 'biofilm', \n",
    "                                    'EPS', 'extracellular polymeric substance', 'curli',  'exopolymer', 'extracellular matrix', 'adhesion', 'colonization', 'attachment'], 'score': 1.2},\n",
    "    'sulfide_production': {'terms': ['sulfide', 'sulfur_reduction', 'desulfovibrio'], 'score': 1.3},\n",
    "    'metal binding / chelation': {'terms': ['metal_chelation', 'metal_binding', 'siderophore', 'complexation',  'chelator', 'metallophore', 'iron complex', 'metal transport'], 'score': 1.0},\n",
    "    'nitrogen_reduction': {'terms': ['denitrification', 'nitrate_reduction', 'nitrite_reduction'], 'score': 1.0},\n",
    "    'manganese_reduction': {'terms': ['manganese_reduction', 'mn_redox', 'manganese oxidation'], 'score': 1.0},\n",
    "    'methanogenesis': {'terms': ['methanogenesis', 'methanobacterium', 'archaea'], 'score': 0.6},\n",
    "    'fumarate_formation': {'terms': ['fumarate', 'propionibacterium'], 'score': 0.5},\n",
    "    'h2_consumption': {'terms': ['h2_consumption', 'hydrogenase', 'hydrogen uptake', 'hydrogen consumption', 'h2', 'H2 oxidation', 'H2ase'], 'score': 0.5},\n",
    "    'o2_consumption': {'terms': ['o2_consumption', 'aerobic_respiration', 'oxygen reduction', 'oxygen consumption'],'score': 0.6}\n",
    "}\n",
    "\n",
    "# 7. CORROSION KEYWORD GROUPS - \n",
    "corrosion_keyword_groups = {\n",
    "    'iron_sulfur_redox': ['iron metabolism', 'sulfur metabolism', 'iron oxidation', 'iron reduction', \n",
    "                            'iron reduc', 'ferric reduc', 'sulfate reduc', 'sulfide', 'sulfite', \n",
    "                            'thiosulfate', 'sulfur oxidation', 'SRB'],\n",
    "    'ocre': ['ocre', 'iron oxide', 'iron deposit', 'metal oxide', 'ochre formation', \n",
    "            'iron oxide deposits', 'iron precipitation', 'rust formation'],\n",
    "    'acid_production': ['acid', 'acidification', 'fermentation', 'lactic acid', 'formic acid', \n",
    "                        'acetic acid', 'oxalic acid', 'organic acid', 'acetate production', \n",
    "                        'lactate metabolism', 'formate production'],\n",
    "    'electron_transfer': ['direct eet', 'redox', 'electron transfer', 'omc', 'deet', 'cytochrome', \n",
    "                            'electron transfer', 'conductive pili', 'nanowire', 'mtrABC', 'omcS', \n",
    "                            'oxidoreductase', 'redox', 'reductase', 'oxidase'],\n",
    "    'biofilm': ['biofilm formation', 'quorum sensing', 'extracellular matrix', 'EPS', \n",
    "                'surface disruption', 'polysaccharide', 'adhesin', 'biofilm', \n",
    "                'extracellular polymeric substance', 'curli', 'exopolymer', 'attachment', 'colonization'],\n",
    "    'sulfide': ['sulfide', 'sulfur reduction', 'desulfovibrio', 'h2s', 'hydrogen sulfide'],\n",
    "    'metal_binding': ['metal chelation', 'metal binding', 'siderophore', 'complexation', \n",
    "                        'chelator', 'metallophore', 'iron complex', 'metal transport'],\n",
    "    'nitrogen': ['denitrification', 'nitrate reduction', 'nitrite reduction', \n",
    "                'nitrogen metabolism', 'nitrate', 'nitrite'],\n",
    "    'manganese': ['manganese reduction', 'mn redox', 'manganese oxidation', 'mn reduction'],\n",
    "    'methanogenesis': ['methanogenesis', 'methanobacterium', 'archaea', 'methane production'],\n",
    "    'fumarate': ['fumarate', 'propionibacterium', 'fumarate reduction'],\n",
    "    'hydrogen': ['h2 consumption', 'hydrogenase', 'hydrogen uptake', 'hydrogen consumption', \n",
    "                'h2', 'h2 oxidation', 'h2ase'],\n",
    "    'oxygen': ['o2 consumption', 'aerobic respiration', 'oxygen reduction', 'oxygen consumption'],\n",
    "    'corrosion_general': ['corrosion', 'deterioration', 'pitting', \n",
    "                            'microbially influenced corrosion','MIC', 'metal deterioration'],\n",
    "    'siderophores_chelators': ['siderophore', 'chelator', 'desferrioxamine', 'deferoxamine', 'desferrioxamine b', 'desferrichrome', 'enterobactin', 'pyoverdine', 'metal chelation']\n",
    "    }\n",
    "\n",
    "# Standard mapping: lower-case keys for matching, with standard symbols as values\n",
    "metal_mapping = {\n",
    "    'iron': 'Fe',\n",
    "    'fe': 'Fe',\n",
    "    'ferrous': 'Fe',\n",
    "    'ferric': 'Fe',\n",
    "    'heme': 'Fe',\n",
    "    'iron-sulfur': 'Fe',\n",
    "    'fe2+': 'Fe',\n",
    "    'fe3+': 'Fe',\n",
    "    'manganese': 'Mn',\n",
    "    'mn': 'Mn',\n",
    "    'manganous': 'Mn',\n",
    "    'manganic': 'Mn',\n",
    "    'manganese oxidation': 'Mn',\n",
    "    'metal oxide': 'Mn',\n",
    "    'copper': 'Cu',\n",
    "    'cu+': 'Cu',\n",
    "    'cu2+': 'Cu',\n",
    "    'nickel': 'Ni',\n",
    "    'ni2+': 'Ni',\n",
    "    'cobalt': 'Co',\n",
    "    'co2+': 'Co',\n",
    "    'zinc': 'Zn',\n",
    "    'zn2+': 'Zn',\n",
    "    'calcium': 'Ca',\n",
    "    'ca2+': 'Ca',\n",
    "    'molybdenum': 'Mo',\n",
    "    'mo': 'Mo',\n",
    "    'vanadium': 'V5+',\n",
    "    'v5+': 'V5+',\n",
    "    'aluminum': 'Al3+',\n",
    "    'al3+': 'Al3+',\n",
    "    'chromium': 'Cr3+',\n",
    "    'cr3+': 'Cr3+',\n",
    "    'sodium': 'Na',\n",
    "    'na+': 'Na',\n",
    "    'nacl': 'Na',\n",
    "    'potassium': 'K',\n",
    "    'k+': 'K',\n",
    "    'kcl': 'K',\n",
    "    'selenium': 'Se',\n",
    "    'se': 'Se',\n",
    "    'barium': 'Ba2+',\n",
    "    'ba2+': 'Ba2+',\n",
    "    'sulfate': 'S',\n",
    "    'sulfide': 'S',\n",
    "    'thiosulfate': 'S',\n",
    "    's-s': 'S',\n",
    "    'sulfur': 'S',\n",
    "    'sulfur oxidation': 'S',\n",
    "    'srb': 'S',\n",
    "    'hydrogen': 'H',\n",
    "    'h2': 'H',\n",
    "    'h2o': 'H',\n",
    "    'h2s': 'H',\n",
    "    'phosfate': 'po4-3',\n",
    "    'nitrate': 'NO3-',\n",
    "    'nitrite': 'NO2',\n",
    "    'chloride': 'Cl-'\n",
    " }"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [],
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 5.585991,
   "end_time": "2025-05-02T10:50:12.623624",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-05-02T10:50:07.037633",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
