# 1. Complete metal_terms 
metal_terms = {	
'iron': ['Fe2+', 'Fe3+', 'iron', 'ferrous', 'ferric', 'heme', 'iron-sulfur', 'rust', 'ochre', 'iron oxide', 'siderophore', 'ferritin'],	
'manganese': ['Mn2+',  'manganese', 'mn', 'manganous', 'manganic', 'manganese oxidation', 'manganese oxide', 'MnO2'],	
'copper': ['Cu+', 'Cu2+', 'copper', 'cupric', 'cuprous', 'copper oxide', 'copper corrosion'],	
'nickel': ['Ni2+', 'nickel', 'nickelous', 'nickel oxidation', 'nickel reduction'],	
'cobalt': ['Co2+',  'cobalt', 'cobaltous', 'cobalamin', 'vitamin B12'],	
'magnesium': ['Mg2+', 'magnesium', 'magnesium oxide'],	
'calcium': ['Ca2+', 'calcium', 'calcium carbonate', 'calcite', 'calcium precipitation'],	
'Mo': ['Mo',  'molybdenum', 'molybdopterin', 'molybdenum cofactor'],	
'V5+': ['V5+', 'vanadium', 'vanadate', 'vanadyl'],	
'Al3+': ['Al3+', 'aluminum', 'aluminate', 'aluminum oxide'],	
'Cr3+': ['Cr3+', 'Cr6+', 'chromium', 'chromate', 'dichromate', 'chromium oxide'],	
'zinc': ['Zn2+', 'zinc', 'zinc finger', 'zinc oxide'],	
'sodium': ['Na+', 'sodium', 'NaCl', 'sodium transport', 'sodium gradient'],	
'potassium': ['K+', 'potassium', 'KCl', 'potassium transport', 'potassium channel'],	
'selenium': ['selenium', 'Se', 'selenocysteine', 'selenoprotein', 'selenite'],	
'barium': ['Ba2+', 'barium', 'barium sulfate', 'barite'],	
'strontium': ['Sr2+', 'strontium', 'strontium carbonate', 'strontium sulfate'], 	
'lead': ['Pb2+', 'Pb4+', 'lead', 'plumbous', 'plumbic', 'lead oxide'], 	
'arsenic': ['As3+', 'As5+', 'arsenic', 'arsenite', 'arsenate', 'arsenic oxidation'], 	
'mercury': ['Hg2+', 'Hg+', 'mercury', 'mercuric', 'mercurous', 'mercury methylation'], 	
}
# Corrosion-specific metal combinations 
corrosion_synergies= {
'Fe-S': ['iron_sulfur', 'Fe-S','iron sulfide','FeS', 'Fe-S cluster'],	
'Fe-Cl': ['iron chloride', 'FeCl', 'iron halide', 'ferric chloride'],	
'Fe-C': ['iron carbon', 'FeC', 'iron carbonate', 'siderite'],	
'Cu-Fe': ['copper iron', 'Cu-Fe', 'bimetallic', 'galvanic couple'],	
'Mn-Fe': ['manganese iron', 'Mn-Fe', 'iron manganese oxide'],
'Ni-Fe': ['Ni-Fe'],  	
'Cr-Fe': ['chromium iron', 'Cr-Fe', 'stainless steel', 'chromium passivation'], 	
'Al-Cu': ['aluminum copper', 'Al-Cu', 'aluminum brass', 'galvanic corrosion'], 	
'Zn-Fe': ['zinc iron', 'Zn-Fe', 'galvanized steel', 'sacrificial anode'],	
'Fe-CO3': ['iron carbonate', 'siderite', 'bicarbonate corrosion', 'carbonate scaling'],	
'Fe-SO4': ['iron sulfate', 'sulfate corrosion', 'gypsum formation'],	
'Fe-Ox': ['iron oxalate', 'oxalate corrosion', 'organic acid', 'oxidation corrosion'],	
'Fe-Ac': ['iron acetate', 'acetate corrosion', 'organic acid', 'oxidation corrosion']}	

# 3. COMPLETE functional_categories with HVAC-corrected scoring and justification
functional_categories =	{
'o2_consumption': {'terms': ['o2_consumption', 'aerobic_respiration', 'oxygen reduction', 'oxygen consumption', 'cytochrome oxidase', 'oxidase', 'terminal oxidase',  'oxygen reductase',  'superoxide dismutase',  'catalase',  'oxidative stress', 'oxygen sensor',  'oxygen tolerance', 'oxygen consum', 'oxygen scavenging', 'oxygen stress', 'peroxidase', 'oxidative phosphorylation', 'NADH dehydrogenase', 'CYTOCHROME-C-OXIDASE','ATPSYN-RXN', 'TCA cycle IV (2-oxoglutarate decarboxylase)','TCA cycle V (2-oxoglutarate:ferredoxin oxidoreductase)',  'TCA cycle VI (obligate autotrophs)', 'TCA cycle VIII (helicobacter)', 'superpathway of glyoxylate bypass and TCA','2-aminophenol degradation',
            'aerobic respiration I (cytochrome c)',
            'catechol degradation I (meta-cleavage pathway)',
            'catechol degradation II (meta-cleavage pathway)',
            'catechol degradation III (ortho-cleavage pathway)',
            'catechol degradation to &beta;-ketoadipate',
            'catechol degradation to 2-oxopent-4-enoate II',
            'chlorosalicylate degradation',
            'glucose degradation (oxidative)',
            'meta cleavage pathway of aromatic compounds',
            'octane oxidation',
            'photorespiration',
            'protocatechuate degradation I (meta-cleavage pathway)',
            'protocatechuate degradation II (ortho-cleavage pathway)',
            'superpathway of aerobic toluene degradation',
            'superpathway of salicylate degradation',
            'syringate degradation',
            'toluene degradation I (aerobic) (via o-cresol)',
            'toluene degradation II (aerobic) (via 4-methylcatechol)',
            'toluene degradation III (aerobic) (via p-cresol)',
            'toluene degradation IV (aerobic) (via catechol)',
            'ubiquinol-10 biosynthesis (prokaryotic)',
            'ubiquinol-7 biosynthesis (prokaryotic)',
            'ubiquinol-8 biosynthesis (prokaryotic)',
            'ubiquinol-9 biosynthesis (prokaryotic)',
            'PWY-5088',
            'PWY-6953',
            'PWY-7110',
            'PWY-7373' ], 'score': 1.2, 'justification': 'Geesey, G.G., Bremer, P.J. (1990). Biofouling of engineered water systems. Biotechnol Bioeng, 36(10):1039-1046'},# VERY HIGH for HVAC - oxygen depletion creates aggressive conditions
'nitrogen_metabolism':  {'terms': ['nitrate_reduction', 'nitrite_reduction', 'denitrification', 'nitrification', 'nitrate respiration', 'nitrite respiration', 'nitrous oxide reduction', 'ammonia oxidation', 'anammox', 'nitrogen fixation', 'ammonification', 'nitrogen metabolism',  'nitrate',  'nitrite','dissimilatory nitrate reduction',  'nitrite reductase', 'nitrate reductase', 'L-arginine biosynthesis II (acetyl cycle)', 'L-ornithine biosynthesis', 'L-histidine biosynthesis', 'L-methionine biosynthesis III', 'L-isoleucine biosynthesis I (from threonine)', 'L-isoleucine biosynthesis II', 'L-isoleucine biosynthesis III', 'L-isoleucine biosynthesis IV', 'L-lysine biosynthesis I', 'L-lysine biosynthesis III', 'L-lysine biosynthesis VI', 'L-valine biosynthesis', 'L-tryptophan biosynthesis', 'superpathway of L-isoleucine biosynthesis I', 'superpathway of L-phenylalanine biosynthesis', 'superpathway of L-tyrosine biosynthesis', 'superpathway of L-threonine biosynthesis', '2-amino-3-carboxymuconate semialdehyde degradation to 2-oxopentenoate',
            '2-nitrobenzoate degradation I',
            '4-aminobutanoate degradation V',
            '5-aminoimidazole ribonucleotide biosynthesis I',
            '5-aminoimidazole ribonucleotide biosynthesis II',
            '8-amino-7-oxonanoate biosynthesis I',
            'ARGDEG-PWY',
            'L-arginine biosynthesis I (via L-ornithine)',
            'L-arginine biosynthesis III (via N-acetyl-L-citrulline)',
            'L-arginine biosynthesis IV (archaebacteria)',
            'L-arginine degradation II (AST pathway)',
            'L-glutamate and L-glutamine biosynthesis',
            'L-glutamate degradation V (via hydroxyglutarate)',
            'L-histidine degradation I',
            'L-histidine degradation II',
            'L-leucine degradation I',
            'L-lysine biosynthesis II',
            'L-tryptophan degradation IX',
            'L-tryptophan degradation XII (Geobacillus)',
            'L-tryptophan degradation to 2-amino-3-carboxymuconate semialdehyde',
            'L-tyrosine degradation I',
            'NAD biosynthesis II (from tryptophan)',
            'ORNARGDEG-PWY',
            'ORNDEG-PWY',
            'allantoin degradation IV (anaerobic)',
            'allantoin degradation to glyoxylate III',
            'arginine, ornithine and proline interconversion',
            'aromatic biogenic amine degradation (bacteria)',
            'aspartate superpathway',
            'creatinine degradation I',
            'creatinine degradation II',
            'ectoine biosynthesis',
            'ergothioneine biosynthesis I (bacteria)',
            'glycine betaine degradation I',
            'inosine-5'-phosphate biosynthesis I',
            'inosine-5'-phosphate biosynthesis III',
            'nicotinate degradation I',
            'nitrate reduction I (denitrification)',
            'nitrate reduction VI (assimilatory)',
            'norspermidine biosynthesis',
            'ppGpp biosynthesis',
            'preQ0 biosynthesis',
            'purine nucleobases degradation I (anaerobic)',
            'purine nucleotides degradation II (aerobic)',
            'purine ribonucleosides degradation',
            'pyridoxal 5'-phosphate biosynthesis I',
            'pyrimidine deoxyribonucleosides salvage',
            'pyrimidine deoxyribonucleotides biosynthesis from CTP',
            'pyrimidine deoxyribonucleotides de novo biosynthesis II',
            'pyrimidine deoxyribonucleotides de novo biosynthesis III',
            'pyrimidine deoxyribonucleotides de novo biosynthesis IV',
            'queuosine biosynthesis',
            'superpathway of L-alanine biosynthesis',
            'superpathway of L-aspartate and L-asparagine biosynthesis',
            'superpathway of L-lysine, L-threonine and L-methionine biosynthesis I',
            'superpathway of L-serine and glycine biosynthesis I',
            'superpathway of arginine and polyamine biosynthesis',
            'superpathway of histidine, purine, and pyrimidine biosynthesis',
            'superpathway of polyamine biosynthesis I',
            'superpathway of polyamine biosynthesis II',
            'superpathway of purine deoxyribonucleosides degradation',
            'superpathway of purine nucleotides de novo biosynthesis I',
            'superpathway of purine nucleotides de novo biosynthesis II',
            'superpathway of pyridoxal 5'-phosphate biosynthesis and salvage',
            'superpathway of pyrimidine deoxyribonucleoside salvage',
            'superpathway of pyrimidine deoxyribonucleosides degradation',
            'superpathway of pyrimidine ribonucleosides salvage',
            'superpathway of thiamin diphosphate biosynthesis I',
            'superpathway of thiamin diphosphate biosynthesis II',
            'tRNA charging',
            'tRNA processing',
            'urea cycle',
            'urate biosynthesis/inosine 5'-phosphate degradation',
            'ILEUDEG-PWY',
            'P163-PWY',
            'P3-PWY',
            'PWY-101',
            'PWY-1422',
            'PWY-5055',
            'PWY-5179',
            'PWY-5308',
            'PWY-5497',
            'PWY-5519',
            'PWY-6145',
            'PWY-6322',
            'PWY-6349',
            'PWY-6581',
            'PWY-6690',
            'PWY-6714',
            'PWY-6834',
            'PWY-6928',
            'PWY-6986',
            'PWY-7015',
            'PWY-7016',
            'PWY-7286',
            'PWY-7287',
            'PWY-7316',
            'PWY-7401',
            'PWY-7528',
            'PWY0-1338',
            'THREOCAT-PWY',
            'VALDEG-PWY' ], 'score': 1.0,'justification': 'Flemming, H.C. (1996). Economically relevant microorganisms in technical systems. Materials and Corrosion, 47(7):391-398 and  Washizu, N., et al. (2004). MIC by nitrate-reducing bacteria in water injection systems. Corrosion, 60(4):336-342'}, # Moderate for HVAC - affects redox conditions	
'iron_metabolism': {'terms': ['corrosion', 'MIC', 'ferric reduc', 'SRB', 'ocre', 'iron_oxide', 'iron_deposit', 'metal oxide', 'ochre formation', 'iron oxide deposits', 'iron precipitation', 'rust formation', 'iron oxid', 'ferrous oxid', 'ferric', 'iron uptake', 'iron transport', 'iron storage',  'iron homeostasis', 'siderophore production', 'iron_sulfur_redox', 'ferredoxin',  'rubredoxin', 'ferritin', 'bacterioferritin',  'PWY-7221',  'PWY-7219', 'HEME-BIOSYNTHESIS-II',  'P125-PWY', 'iron mobilization', 'iron immobilization', 'ferrihydrite', 'goethite', 'magnetite', 'hematite', 'iron mineral', 'biogenic iron oxides', 'stalactite formation', 'ochre mats', 'superpathway of tetrahydrofolate biosynthesis and salvage',  'heme biosynthesis II (anaerobic)', 'tetrapyrrole biosynthesis I (from glutamate)', 'tetrapyrrole biosynthesis II (from glycine)','flavin biosynthesis I (bacteria and plants)','chorismate biosynthesis I', 'chorismate biosynthesis from 3-dehydroquinate', 'enzyme-mediated corrosion', 'AEROBACTINSYN-PWY',
            'enterobactin biosynthesis',
            'heme biosynthesis I (aerobic)',
            'superpathay of heme biosynthesis from glutamate',
            'superpathway of heme biosynthesis from glycine',
            'superpathway of heme biosynthesis from uroporphyrinogen-III',
            'PWY-6516',
            'PWY-7209'], 'score': 1.5, 'justification': 'Beech, I.B., Gaylarde, C.C. (1999). Recent advances in the study of biocorrosion. Rev Microbiol, 30(3):177-190. SRB critical in closed water systems AND Cornell, R.M., Schwertmann, U. (2003). The Iron Oxides. Green rust and iron-organic complexes indicate active corrosion processes'},# represents active Fe-organic complexation '},	# HIGHEST for HVAC - SRB major problem in closed loops
'sulfur_metabolism': {'terms': ['sulphur_metabolism', 'sulfur_metabolism', 'sulfate reduc', 'sulfite', 'thiosulfate', 'sulfur oxidation', 'SRB', 'dsrAB', 'APS reductase', 'sulfide','quinone oxidoreductase', 'dissimilatory sulfate reduction', 'sulfur globules', 'elemental sulfur', 'polysulfide metabolism', 'sulfur granules', 'PWY-6932', 'SO4ASSIM-PWY', 'SULFATE-CYS-PWY', 'sulfide_production', 'sulfonate',  'sulfur_reduction', 'desulfovibrio', 'sulfur disproportionation', 'sulfate-reducing bacteria', 'sulfur respiration', 'sulfate reduction I (assimilatory)', 'superpathway of sulfate assimilation and cysteine biosynthesis', 'L-methionine biosynthesis I',
            'L-methionine salvage cycle III',
            'S-adenosyl-L-methionine cycle I',
            'S-methyl-5-thio-&alpha;-D-ribose 1-phosphate degradation',
            'coenzyme M biosynthesis I',
            'mycothiol biosynthesis',
            'sulfoglycolysis',
            'superpathway of L-methionine biosynthesis (by sulfhydrylation)',
            'superpathway of L-methionine biosynthesis (transsulfuration)',
            'superpathway of S-adenosyl-L-methionine biosynthesis',
            'superpathway of sulfolactate degradation',
            'superpathway of sulfur oxidation (Acidianus ambivalens)',
            'superpathway of taurine degradation',
            'PWY-5327',
            'PWY-5392',
            'PWY-6937'], 'score': 1.5, 'justification': 'Sulfide causes direct corrosive attack on iron and steel surfaces'},# Direct corrosive attack but secondary to SRB iron-sulfur redox
'h2_consumption': {'terms': ['h2_consumption', 'hydrogenase', 'hydrogen uptake', 'hydrogen consumption', 'h2', 'H2 oxidation', 'H2ase', 'hydrogen metabolism', 'hydrogen production',  'FeFe-hydrogenase',  'NiFe-hydrogenase',  'hydrogen evolution',  'hydrogen cycling',  'H2 sensing',  'proton reduction', 'methylerythritol phosphate pathway I', 'methylerythritol phosphate pathway II'], 'score': 0.7, 'justification': 'Javaherdashti, R. (2008). Microbiologically Influenced Corrosion: An Engineering Insight. Springer and Enning, D., Garrelfs, J. (2014). Corrosion of iron by sulfate-reducing bacteria: new views of an old problem. Appl Environ Microbiol, 80(4):1226-1236'},# H2 consumption by SRB accelerates corrosion through cathodic depolarization	
'carbon_metabolism': {'terms': ['carbon_metabolism', 'carbon fixation', 'carbon utilization', 'carbohydrate metabolism', 'glycolysis', 'TCA cycle', 'carbon flux', 'carbon assimilation', 'pentose phosphate pathway', 'gluconeogenesis', 'Calvin cycle', 'reductive acetyl-CoA pathway', 'carbon monoxide dehydrogenase', 'hydrocarbon degradation', 'aromatic degradation', 'alcohol metabolism', 'organic matter degradation', 'VFA production', 'propionate', 'butyrate', 'valerate', 'caproate', 'ACETYL-COA-ACETYLTRANSFER-RXN','METHYLACETOACETYLCOYTHIOL-RXN','ACETOLACTSYN-RXN','ACETOOHBUTSYN-RXN','ACETYL-COA-CARBOXYLTRANSFER-RXN','ACYLCOASYN-RXN','N10-formyl-tetrahydrofolate biosynthesis', 'glycolysis III','Calvin-Benson-Bassham cycle', 'gluconeogenesis', 'glycolysis I (from glucose 6-phosphate)', 'glycolysis II (from fructose 6-phosphate)','glycolysis III (from glucose)','gluconeogenesis I','pentose phosphate pathway (non-oxidative branch)','Calvin-Benson-Bassham cycle','pyruvate fermentation to isobutanol (engineered)','superpathway of branched amino acid biosynthesis','superpathway of aromatic amino acid biosynthesis','superpathway of adenosine nucleotides de novo biosynthesis I','superpathway of adenosine nucleotides de novo biosynthesis II','superpathway of guanosine nucleotides de novo biosynthesis I','superpathway of guanosine nucleotides de novo biosynthesis II', '1,4-dihydroxy-2-naphthoate biosynthesis I',
            '1,4-dihydroxy-6-naphthoate biosynthesis I',
            '1,4-dihydroxy-6-naphthoate biosynthesis II',
            '2-methylcitrate cycle I',
            '2-methylcitrate cycle II',
            '3-hydroxypropanoate cycle',
            '4-coumarate degradation (anaerobic)',
            '4-deoxy-L-threo-hex-4-enopyranuronate degradation',
            '4-methylcatechol degradation (ortho cleavage)',
            'BENZCOA-PWY',
            'Bifidobacterium shunt',
            'CAROTENOID-PWY',
            'CYCLOHEXANOL-OXIDATION-PWY',
            'D-fructuronate degradation',
            'D-galactarate degradation I',
            'D-galacturonate degradation I',
            'D-glucarate degradation I',
            'GLUDEG-II-PWY',
            'HCAMHPDEG-PWY',
            'L-1,2-propanediol degradation',
            'L-arabinose degradation IV',
            'L-rhamnose degradation I',
            'NPGLUCAT-PWY',
            'TCA cycle I (prokaryotic)',
            'TCA cycle VII (acetate-producers)',
            'acetylene degradation',
            'androstenedione degradation',
            'aromatic compounds degradation via &beta;-ketoadipate',
            'benzoyl-CoA degradation I (aerobic)',
            'benzoyl-CoA degradation II (anaerobic)',
            'chitin derivatives degradation',
            'ethylmalonyl-CoA pathway',
            'formaldehyde assimilation II (RuMP Cycle)',
            'formaldehyde oxidation I',
            'fucose degradation',
            'galactose degradation I (Leloir pathway)',
            'gallate degradation I',
            'gallate degradation II',
            'glucose and glucose-1-phosphate degradation',
            'glutaryl-CoA degradation',
            'glycogen biosynthesis I (from ADP-D-Glucose)',
            'glycogen degradation I (bacterial)',
            'glycogen degradation II (eukaryotic)',
            'glyoxylate assimilation',
            'glyoxylate cycle',
            'incomplete reductive TCA cycle',
            'isoprene biosynthesis II (engineered)',
            'ketogluconate metabolism',
            'lactose and galactose degradation I',
            'mandelate degradation I',
            'mandelate degradation to acetyl-CoA',
            'mannan degradation',
            'methanol oxidation to carbon dioxide',
            'methylgallate degradation',
            'mevalonate pathway I',
            'mevalonate pathway II (archaea)',
            'mono-trans, poly-cis decaprenyl phosphate biosynthesis',
            'myo-, chiro- and scillo-inositol degradation',
            'myo-inositol degradation I',
            'nylon-6 oligomer degradation',
            'phenylacetate degradation I (aerobic)',
            'polyisoprenoid biosynthesis (E. coli)',
            'reductive TCA cycle I',
            'reductive acetyl coenzyme A pathway',
            'sitosterol degradation to androstenedione',
            'starch degradation III',
            'starch degradation V',
            'sucrose biosynthesis I (from photosynthesis)',
            'sucrose biosynthesis III',
            'sucrose degradation III (sucrose invertase)',
            'sucrose degradation IV (sucrose phosphorylase)',
            'superpathway of &beta;-D-glucuronide and D-glucuronate degradation',
            'superpathway of D-glucarate and D-galactarate degradation',
            'superpathway of chorismate metabolism',
            'superpathway of demethylmenaquinol-6 biosynthesis I',
            'superpathway of demethylmenaquinol-8 biosynthesis',
            'superpathway of demethylmenaquinol-9 biosynthesis',
            'superpathway of fucose and rhamnose degradation',
            'superpathway of geranylgeranyl diphosphate biosynthesis II (via MEP)',
            'superpathway of geranylgeranyldiphosphate biosynthesis I (via mevalonate)',
            'superpathway of glucose and xylose degradation',
            'superpathway of glycerol degradation to 1,3-propanediol',
            'superpathway of glycol metabolism and degradation',
            'superpathway of glycolysis and Entner-Doudoroff',
            'superpathway of glycolysis, pyruvate dehydrogenase, TCA, and glyoxylate bypass',
            'superpathway of hexitol degradation (bacteria)',
            'superpathway of hexuronide and hexuronate degradation',
            'superpathway of menaquinol-10 biosynthesis',
            'superpathway of menaquinol-11 biosynthesis',
            'superpathway of menaquinol-12 biosynthesis',
            'superpathway of menaquinol-13 biosynthesis',
            'superpathway of menaquinol-6 biosynthesis I',
            'superpathway of menaquinol-7 biosynthesis',
            'superpathway of menaquinol-8 biosynthesis I',
            'superpathway of menaquinol-8 biosynthesis II',
            'superpathway of menaquinol-9 biosynthesis',
            'superpathway of phenylethylamine degradation',
            'superpathway of phylloquinol biosynthesis',
            'superpathway of the 3-hydroxypropanoate cycle',
            'superpathway of ubiquinol-8 biosynthesis (prokaryotic)',
            'superpathway of vanillin and vanillate degradation',
            'taxadiene biosynthesis (engineered)',
            'vanillin and vanillate degradation I',
            'vanillin and vanillate degradation II',
            '4-HYDROXYMANDELATE-DEGRADATION-PWY',
            'P241-PWY',
            'PWY-1622',
            'PWY-1882',
            'PWY-2201',
            'PWY-2221',
            'PWY-2504',
            'PWY-3081',
            'PWY-3801',
            'PWY-3941',
            'PWY-5062',
            'PWY-5184',
            'PWY-5257',
            'PWY-5266',
            'PWY-5273',
            'PWY-5280',
            'PWY-5283',
            'PWY-5306',
            'PWY-5488',
            'PWY-5634',
            'PWY-5656',
            'PWY-5675',
            'PWY-5677',
            'PWY-5724',
            'PWY-5737',
            'PWY-5789',
            'PWY-5823',
            'PWY-5940',
            'PWY-6060',
            'PWY-6113',
            'PWY-6141',
            'PWY-6142',
            'PWY-6143',
            'PWY-6146',
            'PWY-6148',
            'PWY-6165',
            'PWY-6167',
            'PWY-6215',
            'PWY-622',
            'PWY-6281',
            'PWY-6284',
            'PWY-6285',
            'PWY-6324',
            'PWY-6344',
            'PWY-6350',
            'PWY-6374',
            'PWY-6395',
            'PWY-6486',
            'PWY-6538',
            'PWY-6565',
            'PWY-6572',
            'PWY-6583',
            'PWY-6594',
            'PWY-6604',
            'PWY-6629',
            'PWY-6632',
            'PWY-6654',
            'PWY-6655',
            'PWY-6660',
            'PWY-6662',
            'PWY-6676',
            'PWY-6682',
            'PWY-6713',
            'PWY-6728',
            'PWY-6748',
            'PWY-6760',
            'PWY-6785',
            'PWY-6797',
            'PWY-6823',
            'PWY-6830',
            'PWY-6863',
            'PWY-6883',
            'PWY-6886',
            'PWY-6942',
            'PWY-6945',
            'PWY-6946',
            'PWY-6947',
            'PWY-6954',
            'PWY-6956',
            'PWY-6961',
            'PWY-6962',
            'PWY-6977',
            'PWY-6992',
            'PWY-6993',
            'PWY-6999',
            'PWY-7000',
            'PWY-7002',
            'PWY-7020',
            'PWY-7021',
            'PWY-7044',
            'PWY-7084',
            'PWY-7102',
            'PWY-7124',
            'PWY-7128',
            'PWY-7153',
            'PWY-7165',
            'PWY-7185',
            'PWY-7218',
            'PWY-7224',
            'PWY-7274',
            'PWY-7290',
            'PWY-7294',
            'PWY-7312',
            'PWY-7317',
            'PWY-7318',
            'PWY-7385',
            'PWY-7398',
            'PWY-7399',
            'PWY-7402',
            'PWY-7413',
            'PWY-7414',
            'PWY-7483',
            'PWY-7524',
            'PWY-7575',
            'PWY-7596',
            'PWY-7626',
            'PWY-822',
            'PWY0-1277' ], 'score': 0.5,'justification': 'Pope, D.H. (1986). A study of microbiologically influenced corrosion in nuclear power plants. Electric Power Research Institute'},
'organic_acid_metabolism': {'terms':  ['acetate', 'acetic acid', 'acetyl', 'acetate metabolism', 'acetate production', 'oxalate', 'oxalic acid', 'oxalate metabolism', 'oxalate production', 'organic acid', 'fatty acid', 'butyric acid', 'butyrate', 'propionate', 'propionic acid', 'carboxylic acid', 'lactate', 'lactic acid', 'formate', 'formic acid', 'citrate', 'citric acid', 'succinate', 'succinic acid', 'fumarate', 'fumaric acid', 'malate', 'malic acid', 'pyruvate', 'pyruvic acid', 'acidification', 'fermentation', 'CENTFERM-PWY', 'FERMENTATION-PWY', 'GLYCOLYSIS', 'PWY-5100', 'GALACTUROCAT-PWY', 'fatty acid β-oxidation I', 'fatty acid elongation','fatty acid salvage','stearate biosynthesis II (bacteria and plants)','palmitoleate biosynthesis I (from (5Z)-dodec-5-enoate)','cis-vaccenate biosynthesis','oleate biosynthesis IV (anaerobic)','gondoate biosynthesis (anaerobic)','mycolate biosynthesis', '3-phenylpropanoate degradation',
            '4-hydroxyphenylacetate degradation',
            'METHGLYUT-PWY',
            'PROPFERM-PWY',
            'acetyl-CoA fermentation to butanoate II',
            'glycerol degradation to butanol',
            'heterolactic fermentation',
            'hexitol fermentation to lactate, formate, ethanol and acetate',
            'homolactic fermentation',
            'isopropanol biosynthesis',
            'methyl ketone biosynthesis',
            'mixed acid fermentation',
            'pyruvate fermentation to acetate and lactate II',
            'pyruvate fermentation to acetone',
            'pyruvate fermentation to butanoate',
            'pyruvate fermentation to propanoate I',
            'superpathway of Clostridium acetobutylicum acidogenic fermentation',
            'superpathway of (R,R)-butanediol biosynthesis',
            'superpathway of 2,3-butanediol biosynthesis',
            'PWY-5751',
            'PWY-5757'], 'score': 1.4, 'justification': 'Videla, H.A., Herrera, L.K. (2005). Microbiologically influenced corrosion: looking to the future. Int Microbiol, 8(3):169-180'}, # VERY HIGH for HVAC - organic acids major issue	
'metal_binding_chelation': {'terms': ['metal_chelation', 'metal_binding', 'siderophore', 'complexation', 'iron chelation', 'enzymatic_metal_oxid',   'chelator', 'metallophore', 'iron complex', 'metal transport', 'metal oxide', 'iron oxide deposits', 'metal deposition', 'metal solubilization', 'mineral dissolution', 'mineral precipitation', 'chelation', 'metal complexation', 'metal sequestration' , 'metal_organic_interaction', 'metal organic', 'metal homeostasis', 'organometallic',  'iron uptake', 'metal uptake', 'metalloprotein',  'iron-sulfur cluster', 'metal coordination', 'ferric reductase', 'ferrous oxidase', 'metal homeostasis', 'mineral dissolution', 'laccase', 'mineral precipitation', 'copper reduction', 'nickel oxidation', 'chromium reduction', 'crystal nucleation', 'metal immobilization', 'coenzyme A biosynthesis I','pantothenate and coenzyme A biosynthesis I','phosphopantothenate biosynthesis I','NAD biosynthesis I (from aspartate)','thiamin salvage II', 'metalloenzyme', 'enzyme-catalyzed oxidation', '6-hydroxymethyl-dihydropterin diphosphate biosynthesis I',
            '6-hydroxymethyl-dihydropterin diphosphate biosynthesis III (Chlamydia)',
            'adenosylcobalamin biosynthesis I (early cobalt insertion)',
            'adenosylcobalamin biosynthesis II (late cobalt incorporation)',
            'adenosylcobalamin biosynthesis from cobyrinate a,c-diamide I',
            'adenosylcobalamin salvage from cobinamide I',
            'adenosylcobalamin salvage from cobinamide II',
            'biotin biosynthesis I',
            'biotin biosynthesis II',
            'chlorophyllide a biosynthesis I (aerobic, light-dependent)',
            'chlorophyllide a biosynthesis II (anaerobic)',
            'chlorophyllide a biosynthesis III (aerobic, light independent)',
            'cob(II)yrinate a,c-diamide biosynthesis I (early cobalt insertion)',
            'cob(II)yrinate a,c-diamide biosynthesis II (late cobalt incorporation)',
            'superpathway of bacteriochlorophyll a biosynthesis',
            'superpathway of tetrahydrofolate biosynthesis',
            'thiazole biosynthesis I (E. coli)',
            'thiazole biosynthesis II (Bacillus)',
            'P181-PWY',
            'P341-PWY',
            'PHOTOALL-PWY'], 'score': 1.2, 'justification': 'Herrera, L.K., Videla, H.A. (2009). Role of iron-reducing bacteria in corrosion and protection of carbon steel. Int Biodeterior Biodegradation, 63(7):891-895'},# Important in closed loops
'biofilm_formation': {'terms': ['biofilm_formation', 'metal_chelation', 'quorum_sensing', 'extracellular_matrix', 'exopolysaccharide', 'EPS production', 'EPS', 'surface_disruption', 'polysaccharide', 'adhesin', 'biofilm', 'EPS', 'extracellular polymeric substance', 'curli', 'exopolymer','extracellular matrix', 'adhesion', 'colonization', 'attachment', 'surface', 'adherence', 'biofilm maturation', 'biofilm regulation', 'biofilm dispersion', 'cell-cell adhesion', 'surface attachment', 'polysaccharide biosynthesis', 'cell aggregation', 'matrix production', 'pellicle', 'floc formation', 'COLANSYN-PWY', 'EXOPOLYSACC-PWY', 'GLUCOSE1PMETAB-PWY', 'alginate', 'cellulose', 'lipid metabolism', 'fatty acid synthesis', 'fatty acid degradation', 'biosurfactant', 'VFA', 'volatile fatty acid', 'propionate', 'butyrate', 'oleaginous', 'lipid accumulation', '3-oxoacyl', '3-oxoacyl-(acyl-carrier-protein)','3-oxocerotoyl-[acp] reductase','3-oxo-cis-Δ7-tetradecenoyl-[acp] reductase','3-oxo-cis-Δ9-hexadecenoyl-[acp] reductase','3-oxo-glutaryl-[acp] methyl ester reductase','3-oxo-pimeloyl-[acp] methyl ester reductase','3-oxo-docosapentaenoyl [acp][c]','(5Z)-3-oxo-tetradec-5-enoyl-[acyl-carrier-protein] reductase','(7Z)-3-oxo-hexadec-7-enoyl-[acp] reductase','(9Z)-3-oxo-octadec-9-enoyl-[acp] reductase','(11Z)-3-oxo-icos-11-enoyl-[acp] reductase','acetoacetyl-[acyl-carrier protein] reductase','3-hydroxyhexanoyl-[acyl-carrier protein] reductase','3-oxo-octanoyl-[acyl-carrier protein] reductase','3-oxo-decanoyl-[acyl-carrier protein] reductase','LINOLENOYL-RXN', 'coenzyme A biosynthesis I', 'peptidoglycan biosynthesis I (meso-diaminopimelate containing)','peptidoglycan biosynthesis III (mycobacteria)','UDP-N-acetylmuramoyl-pentapeptide biosynthesis I (meso-diaminopimelate containing)','UDP-N-acetylmuramoyl-pentapeptide biosynthesis II (lysine-containing)','dTDP-L-rhamnose biosynthesis I','O-antigen building blocks biosynthesis (E. coli)','phosphatidylglycerol biosynthesis I (plastidic)','phosphatidylglycerol biosynthesis II (non-plastidic)','CDP-diacylglycerol biosynthesis I','CDP-diacylglycerol biosynthesis II', '(5Z)-dodec-5-enoate biosynthesis',
            'ADP-L-glycero-&beta;-D-manno-heptose biosynthesis',
            'CMP-3-deoxy-D-manno-octulosonate biosynthesis I',
            'CMP-legionaminate biosynthesis I',
            'ECASYN-PWY',
            'GDP-D-glycero-&alpha;-D-manno-heptose biosynthesis',
            'GDP-mannose biosynthesis',
            'Kdo transfer to lipid IVA III (Chlamydia)',
            'LIPASYN-PWY',
            'LPSSYN-PWY',
            'UDP-2,3-diacetamido-2,3-dideoxy-&alpha;-D-mannuronate biosynthesis',
            'UDP-N-acetyl-D-glucosamine biosynthesis I',
            'adenine and adenosine salvage III',
            'adenosine nucleotides degradation II',
            'anhydromuropeptides recycling',
            'colanic acid building blocks biosynthesis',
            'dTDP-N-acetylthomosamine biosynthesis',
            'fatty acid &beta;-oxidation I',
            'fatty acid elongation -- saturated',
            'guanosine nucleotides degradation III',
            'lipid IVA biosynthesis',
            'mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
            'palmitate biosynthesis II (bacteria and plants)',
            'peptidoglycan biosynthesis II (staphylococci)',
            'peptidoglycan biosynthesis IV (Enterococcus faecium)',
            'peptidoglycan biosynthesis V (&beta;-lactam resistance)',
            'peptidoglycan maturation (meso-diaminopimelate containing)',
            'superpathway of (Kdo)2-lipid A biosynthesis',
            'superpathway of GDP-mannose-derived O-antigen building blocks biosynthesis',
            'superpathway of N-acetylglucosamine, N-acetylmannosamine and N-acetylneuraminate degradation',
            'superpathway of N-acetylneuraminate degradation',
            'superpathway of UDP-N-acetylglucosamine-derived O-antigen building blocks biosynthesis',
            'superpathway of UDP-glucose-derived O-antigen building blocks biosynthesis',
            'superpathway of fatty acid biosynthesis initiation (E. coli)',
            'superpathway of mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
            'superpathway of phospholipid biosynthesis I (bacteria)',
            'teichoic acid (poly-glycerol) biosynthesis'], 'score': 1.3, 'justification': 'Borenstein, S.W. (1994). Microbiologically Influenced Corrosion Handbook. Industrial Press. Biofilms critical in closed water systems'},#  biofilms major problem in closed systems	
'manganese_processes': {'terms': ['manganese_reduction', 'mn_redox', 'manganese oxidation', 'manganese oxide',  'pyrolusite',  'birnessite',  'manganese cycling',  'manganese mineral',  'manganese transport', 'Mn-oxide formation', 'Mn-oxide reduction', 'Mn precipitation', 'Mn dissolution'],'score': 1.0,'justification': 'Tebo, B.M., et al. (2004). Biogenic manganese oxides: properties and mechanisms of formation. Annu Rev Earth Planet Sci, 32:287-328'}, 
'methanogenesis': {'terms': ['methanogenesis', 'methanobacterium', 'archaea', 'methane production', 'methyl-coenzyme M reductase', 'methanogenic', 'coenzyme F420',  'methyl-H4MPT', 'CO2 reduction', 'acetoclastic methanogenesis',  'METHANOGENESIS-PWY',
            'methanogenesis from acetate'],'score': 0.6,'justification': 'Mori, K., et al. (2010). Methanogens in microbiologically influenced corrosion: a review. Microorganisms, 8(7):995'},# REDUCED for HVAC - uncommon in aerobic systems	
'fumarate_formation': {'terms': ['fumarate', 'propionibacterium'],  'score': 0.5},# Lower priority in HVAC. 
'phosphorus_metabolism': {'terms': ['phosphate transport',  'polyphosphate', 'phosphite oxidation', 'organophosphonate metabolism',  'UMP biosynthesis', 'pyrimidine deoxyribonucleotides de novo biosynthesis I','pyrimidine deoxyribonucleotide phosphorylation','superpathway of pyrimidine nucleobases salvage','superpathway of pyrimidine deoxyribonucleotides de novo biosynthesis','adenosine ribonucleotides de novo biosynthesis','adenosine deoxyribonucleotides de novo biosynthesis II','guanosine ribonucleotides de novo biosynthesis','guanosine deoxyribonucleotides de novo biosynthesis II','superpathway of pyrimidine ribonucleotides de novo biosynthesis','superpathway of pyrimidine deoxyribonucleotides de novo biosynthesis (E. coli)', 'NAD salvage pathway I',
            'NAD salvage pathway II',
            'methylphosphonate degradation I'], 'score': 0.5,'justification': 'Beech, I.B., Sunner, J. (2004). Biocorrosion: towards understanding interactions between biofilms and metals. Curr Opin Biotechnol, 15(3):181-186'},	
}

# 4.The following is a mapping no a dictionary 
metal_mapping = {
'iron': 'Fe',
'fe': 'Fe',
'ferrous': 'Fe',
'ferric': 'Fe',
'heme': 'Fe',
'iron-sulfur': 'Fe',
'fe2+': 'Fe',
'fe3+': 'Fe',
'manganese': 'Mn',
'mn': 'Mn',
'manganous': 'Mn',
'manganic': 'Mn',
'manganese oxidation': 'Mn',
'metal oxide': 'Mn',
'copper': 'Cu',
'cu+': 'Cu',
'cu2+': 'Cu',
'nickel': 'Ni',
'ni2+': 'Ni',
'cobalt': 'Co',
'co2+': 'Co',
'zinc': 'Zn',
'zn2+': 'Zn',
'calcium': 'Ca',
'ca2+': 'Ca',
'molybdenum': 'Mo',
'mo': 'Mo',
'vanadium': 'V5+',
'v5+': 'V5+',
'aluminum': 'Al3+',
'al3+': 'Al3+',
'chromium': 'Cr3+',
'cr3+': 'Cr3+',
'sodium': 'Na',
'na+': 'Na',
'nacl': 'Na',
'potassium': 'K',
'k+': 'K',
'kcl': 'K',
'selenium': 'Se',
'se': 'Se',
'barium': 'Ba2+',
'ba2+': 'Ba2+',
'sulfate': 'S',
'sulfide': 'S',
'thiosulfate': 'S',
's-s': 'S',
'sulfur': 'S',
'sulfur oxidation': 'S',
'srb': 'S',
'hydrogen': 'H',
'h2': 'H',
'h2o': 'H',
'h2s': 'H',
'phosphate': 'po4-3',
'nitrate': 'NO3-',
'nitrite': 'NO2',
'chloride': 'Cl-'
}
# 5. Complete corrosion_mechanisms, no to be use on scoring system
# bridging thegap betwen the metabolic potential (pathways) and the actual physical or chemical effects on a surface.

corrosion_mechanisms = {
    'o2_consumption': [
        '2-aminophenol degradation',
        'PWY-5088',
        'PWY-6953',
        'PWY-7110',
        'PWY-7373',
        'aerobic respiration',
        'aerobic respiration I (cytochrome c)',
        'benzoyl-CoA degradation I (aerobic)',
        'catechol degradation I (meta-claevage pathway)',
        'catechol degradation II (meta-cleavage pathway)',
        'catechol degradation III (ortho-cleavage pathway)',
        'catechol degradation to &beta;-ketoadipate',
        'catechol degradation to 2-oxopent-4-enoate II',
        'chlorosalicylate degradation',
        'gallate degradation I',
        'gallate degradation II',
        'glucose degradation (oxidative)',
        'heme biosynthesis I (aerobic)',
        'meta cleavage pathway of aromatic compounds',
        'methylgallate degradation',
        'octane oxidation',
        'oxidase',
        'oxidative phosphorylation',
        'oxygen consumtion',
        'oxygen depletion',
        'oxygen reduction',
        'oxygen scavenging',
        'oxygen stress',
        'phenylacetate degradation I (aerobic)',
        'photorespiration',
        'protocatechuate degradation I (meta-cleavage pathway)',
        'protocatechuate degradation II (ortho-cleavage pathway)',
        'respiratory burst',
        'superpathway of aerobic toluene degradation',
        'superpathway of salicylate degradation',
        'syringate degradation',
        'toluene degradation I (aerobic) (via o-cresol)',
        'toluene degradation II (aerobic) (via 4-methylcatechol)',
        'toluene degradation III (aerobic) (via p-cresol)',
        'toluene degradation IV (aerobic) (via catechol)',
        'vanillin and vanillate degradation I'
    ],
    'nitrogen_metabolism': [
        '2-amino-3-carboxymuconate semialdehyde degradation to 2-oxopentenoate',
        '2-nitrobenzoate degradation I',
        '4-aminobutanoate degradation V',
        'ARGDEG-PWY',
        'ILEUDEG-PWY',
        'L-arginine biosynthesis I (via L-ornithine)',
        'L-arginine biosynthesis III (via N-acetyl-L-citrulline)',
        'L-arginine biosynthesis IV (archaebacteria)',
        'L-arginine degradation II (AST pathway)',
        'L-glutamate and L-glutamine biosynthesis',
        'L-glutamate degradation V (via hydroxyglutarate)',
        'L-histidine degradation I',
        'L-histidine degradation II',
        'L-leucine degradation I',
        'L-lysine biosynthesis II',
        'L-tryptophan degradation IX',
        'L-tryptophan degradation XII (Geobacillus)',
        'L-tryptophan degradation to 2-amino-3-carboxymuconate semialdehyde',
        'L-tyrosine degradation I',
        'NAD biosynthesis II (from tryptophan)',
        'ORNARGDEG-PWY',
        'ORNDEG-PWY',
        'P163-PWY',
        'P3-PWY',
        'PWY-101',
        'PWY-1422',
        'PWY-5055',
        'PWY-5179',
        'PWY-5308',
        'PWY-5497',
        'PWY-5519',
        'PWY-6145',
        'PWY-6322',
        'PWY-6349',
        'PWY-6581',
        'PWY-6690',
        'PWY-6714',
        'PWY-6834',
        'PWY-6928',
        'PWY-6986',
        'PWY-7015',
        'PWY-7016',
        'PWY-7286',
        'PWY-7287',
        'PWY-7316',
        'PWY-7401',
        'PWY-7528',
        'PWY0-1338',
        'THREOCAT-PWY',
        'VALDEG-PWY',
        'allantoin degradation IV (anaerobic)',
        'allantoin degradation to glyoxylate III',
        'ammonia oxidation',
        'ammonification',
        'anammox',
        'arginine, ornithine and proline interconversion',
        'aromatic biogenic amine degradation (bacteria)',
        'aspartate superpathway',
        'creatinine degradation I',
        'creatinine degradation II',
        'denitrification',
        'ectoine biosynthesis',
        'nicotinate degradation I',
        'nitrate reduction',
        'nitrate reduction I (denitrification)',
        'nitrate reduction VI (assimilatory)',
        'nitrate respiration',
        'nitrification',
        'nitrite reduction',
        'nitrite respiration',
        'nitrogen fixation',
        'norspermidine biosynthesis',
        'nitrous oxide reduction',
        'superpathway of L-alanine biosynthesis',
        'superpathway of L-aspartate and L-asparagine biosynthesis',
        'superpathway of L-lysine, L-threonine and L-methionine biosynthesis I',
        'superpathway of L-serine and glycine biosynthesis I',
        'superpathway of arginine and polyamine biosynthesis',
        'superpathway of histidine, purine, and pyrimidine biosynthesis',
        'superpathway of polyamine biosynthesis I',
        'superpathway of polyamine biosynthesis II',
        'urea cycle'
    ],
    'iron_metabolism': [
        'AEROBACTINSYN-PWY',
        'PWY-6516',
        'PWY-7209',
        'bacterioferritin',
        'enterobactin biosynthesis',
        'ferric reducction',
        'ferritin',
        'ferrous oxidation',
        'heme biosynthesis',
        'heme biosynthesis I (aerobic)',
        'iron homeostasis',
        'iron oxidation',
        'iron reducction',
        'iron storage',
        'iron transport',
        'iron uptake',
        'iron-sulfur cluster',
        'siderophore production',
        'superpathay of heme biosynthesis from glutamate',
        'superpathway of heme biosynthesis from glycine',
        'superpathway of heme biosynthesis from uroporphyrinogen-III'
    ],
    'sulfur_metabolism': [
        'L-methionine biosynthesis I',
        'L-methionine salvage cycle III',
        'PWY-5327',
        'PWY-5392',
        'PWY-6937',
        'S-adenosyl-L-methionine cycle I',
        'S-methyl-5-thio-&alpha;-D-ribose 1-phosphate degradation',
        'SRB',
        'coenzyme M biosynthesis I',
        'elemental sulfur',
        'mycothiol biosynthesis',
        'polysulfide',
        'sulfate reduc',
        'sulfate reduction I (assimilatory)',
        'sulfate-reducing bacteria',
        'sulfide',
        'sulfite',
        'sulfite reduction',
        'sulfoglycolysis',
        'sulfur disproportionation',
        'sulfur oxidation',
        'sulfur respiration',
        'superpathway of L-methionine biosynthesis (by sulfhydrylation)',
        'superpathway of L-methionine biosynthesis (transsulfuration)',
        'superpathway of S-adenosyl-L-methionine biosynthesis',
        'superpathway of sulfate assimilation and cysteine biosynthesis',
        'superpathway of sulfolactate degradation',
        'superpathway of sulfur oxidation (Acidianus ambivalens)',
        'superpathway of taurine degradation',
        'thiosulfate'
    ],
    'h2_consumption': [
        'H2 oxidation',
        'H2ase',
        'METHANOGENESIS-PWY',
        'h2',
        'hydrogen consumption',
        'hydrogen metabolism',
        'hydrogen uptake',
        'hydrogenase',
        'methanogenesis from acetate'
    ],
    'carbon_metabolism': [
        '1,4-dihydroxy-2-naphthoate biosynthesis I',
        '1,4-dihydroxy-6-naphthoate biosynthesis I',
        '1,4-dihydroxy-6-naphthoate biosynthesis II',
        '4-coumarate degradation (anaerobic)',
        '4-deoxy-L-threo-hex-4-enopyranuronate degradation',
        'BENZCOA-PWY',
        'Bifidobacterium shunt',
        'CAROTENOID-PWY',
        'D-fructuronate degradation',
        'D-galactarate degradation I',
        'D-galacturonate degradation I',
        'D-glucarate degradation I',
        'GLUDEG-II-PWY',
        'HCAMHPDEG-PWY',
        'L-1,2-propanediol degradation',
        'L-arabinose degradation IV',
        'L-rhamnose degradation I',
        'NPGLUCAT-PWY',
        'P241-PWY',
        'PWY-1622',
        'PWY-1882',
        'PWY-2201',
        'PWY-2221',
        'PWY-2504',
        'PWY-3081',
        'PWY-3801',
        'PWY-3941',
        'PWY-5062',
        'PWY-5184',
        'PWY-5257',
        'PWY-5266',
        'PWY-5273',
        'PWY-5280',
        'PWY-5283',
        'PWY-5306',
        'PWY-5488',
        'PWY-5634',
        'PWY-5656',
        'PWY-5675',
        'PWY-5677',
        'PWY-5724',
        'PWY-5737',
        'PWY-5789',
        'PWY-5823',
        'PWY-5940',
        'PWY-6060',
        'PWY-6113',
        'PWY-6141',
        'PWY-6142',
        'PWY-6143',
        'PWY-6146',
        'PWY-6148',
        'PWY-6165',
        'PWY-6167',
        'PWY-6215',
        'PWY-622',
        'PWY-6281',
        'PWY-6284',
        'PWY-6285',
        'PWY-6324',
        'PWY-6344',
        'PWY-6350',
        'PWY-6374',
        'PWY-6395',
        'PWY-6486',
        'PWY-6538',
        'PWY-6565',
        'PWY-6572',
        'PWY-6583',
        'PWY-6594',
        'PWY-6604',
        'PWY-6629',
        'PWY-6632',
        'PWY-6654',
        'PWY-6655',
        'PWY-6660',
        'PWY-6662',
        'PWY-6676',
        'PWY-6682',
        'PWY-6713',
        'PWY-6728',
        'PWY-6748',
        'PWY-6760',
        'PWY-6785',
        'PWY-6797',
        'PWY-6823',
        'PWY-6830',
        'PWY-6863',
        'PWY-6883',
        'PWY-6886',
        'PWY-6942',
        'PWY-6945',
        'PWY-6946',
        'PWY-6947',
        'PWY-6954',
        'PWY-6956',
        'PWY-6961',
        'PWY-6962',
        'PWY-6977',
        'PWY-6992',
        'PWY-6993',
        'PWY-6999',
        'PWY-7000',
        'PWY-7002',
        'PWY-7020',
        'PWY-7021',
        'PWY-7044',
        'PWY-7084',
        'PWY-7102',
        'PWY-7124',
        'PWY-7128',
        'PWY-7153',
        'PWY-7165',
        'PWY-7185',
        'PWY-7218',
        'PWY-7224',
        'PWY-7274',
        'PWY-7290',
        'PWY-7294',
        'PWY-7312',
        'PWY-7317',
        'PWY-7318',
        'PWY-7385',
        'PWY-7398',
        'PWY-7399',
        'PWY-7402',
        'PWY-7413',
        'PWY-7414',
        'PWY-7483',
        'PWY-7524',
        'PWY-7575',
        'PWY-7596',
        'PWY-7626',
        'PWY-822',
        'PWY0-1277',
        'TCA cycle',
        'acetylene degradation',
        'androstenedione degradation',
        'benzoyl-CoA degradation II (anaerobic)',
        'carbohydrate metabolism',
        'carbon assimilation',
        'carbon catabolite repression',
        'carbon fixation',
        'carbon flux',
        'carbon utilization',
        'carbonation',
        'carbonate precipitation',
        'chitin derivatives degradation',
        'ethylmalonyl-CoA pathway',
        'fucose degradation',
        'galactose degradation I (Leloir pathway)',
        'glucose and glucose-1-phosphate degradation',
        'glutaryl-CoA degradation',
        'glycolysis',
        'glyoxylate cycle',
        'ketogluconate metabolism',
        'lactose and galactose degradation I',
        'mandelate degradation I',
        'mandelate degradation to acetyl-CoA',
        'mannan degradation',
        'methanol oxidation to carbon dioxide',
        'mevalonate pathway I',
        'mevalonate pathway II (archaea)',
        'myo-, chiro- and scillo-inositol degradation',
        'myo-inositol degradation I',
        'nylon-6 oligomer degradation',
        'reductive acetyl coenzyme A pathway',
        'sitosterol degradation to androstenedione',
        'starch degradation III',
        'starch degradation V',
        'sucrose degradation III (sucrose invertase)',
        'sucrose degradation IV (sucrose phosphorylase)',
        'superpathway of &beta;-D-glucuronide and D-glucuronate degradation',
        'superpathway of D-glucarate and D-galactarate degradation',
        'superpathway of fucose and rhamnose degradation',
        'superpathway of glucose and xylose degradation',
        'superpathway of glycerol degradation to 1,3-propanediol',
        'superpathway of glycol metabolism and degradation',
        'superpathway of glycolysis and Entner-Doudoroff',
        'superpathway of glycolysis, pyruvate dehydrogenase, TCA, and glyoxylate bypass',
        'superpathway of hexitol degradation (bacteria)',
        'superpathway of hexuronide and hexuronate degradation',
        'superpathway of phenylethylamine degradation',
        'superpathway of vanillin and vanillate degradation',
        'taxadiene biosynthesis (engineered)',
        'vanillin and vanillate degradation II'
    ],
    'acid_production': [
        '2-methylcitrate cycle I',
        '2-methylcitrate cycle II',
        '3-hydroxypropanoate cycle',
        '3-phenylpropanoate degradation',
        '4-HYDROXYMANDELATE-DEGRADATION-PWY',
        'METHGLYUT-PWY',
        'PROPFERM-PWY',
        'PWY-5751',
        'PWY-5757',
        'TCA cycle I (prokaryotic)',
        'TCA cycle VII (acetate-producers)',
        'acetate production',
        'acetic acid',
        'acetyl-CoA fermentation to butanoate II',
        'acid',
        'acidification',
        'carbonic acid',
        'citric acid',
        'fermentation',
        'formate production',
        'formic acid',
        'gluconic acid',
        'glycerol degradation to butanol',
        'heterolactic fermentation',
        'hexitol fermentation to lactate, formate, ethanol and acetate',
        'homolactic fermentation',
        'incomplete reductive TCA cycle',
        'isopropanol biosynthesis',
        'lactic acid',
        'lactate metabolism',
        'low pH',
        'methyl ketone biosynthesis',
        'mixed acid fermentation',
        'organic acid',
        'oxalic acid',
        'proton generation',
        'pyruvate fermentation to acetate and lactate II',
        'pyruvate fermentation to acetone',
        'pyruvate fermentation to butanoate',
        'pyruvate fermentation to propanoate I',
        'reductive TCA cycle I',
        'superpathway of (R,R)-butanediol biosynthesis',
        'superpathway of 2,3-butanediol biosynthesis',
        'superpathway of Clostridium acetobutylicum acidogenic fermentation',
        'superpathway of the 3-hydroxypropanoate cycle'
    ],
    'metal_chelation': [
        '6-hydroxymethyl-dihydropterin diphosphate biosynthesis I',
        '6-hydroxymethyl-dihydropterin diphosphate biosynthesis III (Chlamydia)',
        'P181-PWY',
        'P341-PWY',
        'PHOTOALL-PWY',
        'adenosylcobalamin biosynthesis I (early cobalt insertion)',
        'adenosylcobalamin biosynthesis II (late cobalt incorporation)',
        'adenosylcobalamin biosynthesis from cobyrinate a,c-diamide I',
        'adenosylcobalamin salvage from cobinamide I',
        'adenosylcobalamin salvage from cobinamide II',
        'biotin biosynthesis I',
        'biotin biosynthesis II',
        'chelate formation',
        'chelator',
        'chelation',
        'chlorophyllide a biosynthesis I (aerobic, light-dependent)',
        'chlorophyllide a biosynthesis II (anaerobic)',
        'chlorophyllide a biosynthesis III (aerobic, light independent)',
        'cob(II)yrinate a,c-diamide biosynthesis I (early cobalt insertion)',
        'cob(II)yrinate a,c-diamide biosynthesis II (late cobalt incorporation)',
        'iron complex',
        'metal binding',
        'metal complexation',
        'metal ligand',
        'metal sequestration',
        'metal transport',
        'metallophore',
        'siderophore',
        'superpathway of bacteriochlorophyll a biosynthesis',
        'superpathway of tetrahydrofolate biosynthesis',
        'thiazole biosynthesis I (E. coli)',
        'thiazole biosynthesis II (Bacillus)'
    ],
    'biofilm_formation': [
        '(5Z)-dodec-5-enoate biosynthesis',
        'ADP-L-glycero-&beta;-D-manno-heptose biosynthesis',
        'AI-2',
        'AHL',
        'CDP-diacylglycerol biosynthesis I',
        'CDP-diacylglycerol biosynthesis II',
        'CMP-3-deoxy-D-manno-octulosonate biosynthesis I',
        'CMP-legionaminate biosynthesis I',
        'ECASYN-PWY',
        'EPS',
        'GDP-D-glycero-&alpha;-D-manno-heptose biosynthesis',
        'GDP-mannose biosynthesis',
        'Kdo transfer to lipid IVA III (Chlamydia)',
        'LIPASYN-PWY',
        'LPSSYN-PWY',
        'O-antigen building blocks biosynthesis (E. coli)',
        'UDP-2,3-diacetamido-2,3-dideoxy-&alpha;-D-mannuronate biosynthesis',
        'UDP-N-acetyl-D-glucosamine biosynthesis I',
        'acyl homoserine lactone',
        'adherence',
        'adhesin',
        'adhesion',
        'alginate production',
        'anhydromuropeptides recycling',
        'attachment',
        'autoinducer',
        'biofilm',
        'biofilm architecture',
        'biofilm dispersal',
        'biofilm matrix',
        'biofilm maturation',
        'biofilm regulation',
        'c-di-GMP',
        'cellulose production',
        'colanic acid building blocks biosynthesis',
        'colonization',
        'curli',
        'dTDP-N-acetylthomosamine biosynthesis',
        'eDNA',
        'exopolymer',
        'exopolysaccharide',
        'extracellular DNA',
        'extracellular matrix',
        'extracellular polymeric substance',
        'fatty acid &beta;-oxidation I',
        'fatty acid elongation -- saturated',
        'lipid IVA biosynthesis',
        'matrix metalloprotease',
        'mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
        'palmitate biosynthesis II (bacteria and plants)',
        '(p)ppGpp',
        'peptidoglycan biosynthesis II (staphylococci)',
        'peptidoglycan biosynthesis IV (Enterococcus faecium)',
        'peptidoglycan biosynthesis V (&beta;-lactam resistance)',
        'peptidoglycan maturation (meso-diaminopimelate containing)',
        'polysaccharide',
        'quorum sensing',
        'stringent response',
        'superpathway of (Kdo)2-lipid A biosynthesis',
        'superpathway of GDP-mannose-derived O-antigen building blocks biosynthesis',
        'superpathway of N-acetylglucosamine, N-acetylmannosamine and N-acetylneuraminate degradation',
        'superpathway of N-acetylneuraminate degradation',
        'superpathway of UDP-N-acetylglucosamine-derived O-antigen building blocks biosynthesis',
        'superpathway of UDP-glucose-derived O-antigen building blocks biosynthesis',
        'superpathway of fatty acid biosynthesis initiation (E. coli)',
        'superpathway of mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
        'superpathway of phospholipid biosynthesis I (bacteria)',
        'surface',
        'teichoic acid (poly-glycerol) biosynthesis'
    ],
    'manganese_metabolism': [
        'Mn cycling',
        'Mn precipitation',
        'Mn-oxide dissolution',
        'Mn-oxide formation',
        'birnessite formation',
        'manganese oxidation',
        'manganese reduction',
        'pyrolusite formation'
    ],
    'metal_transformation': [
        'NAD salvage pathway I',
        'NAD salvage pathway II',
        'biosorption',
        'co-precipitation',
        'iron oxide deposits',
        'iron precipitation',
        'iron reduction',
        'manganese oxidation',
        'metal deposition',
        'metal mobilization',
        'metal oxide',
        'metal solubilization',
        'methylphosphonate degradation I',
        'mineral dissolution',
        'mineral precipitation',
        'ochre formation',
        'rust formation'
    ]
}

#===============================================
# 6. Complete updated pathway_categories dictionary , no to be use on scoring system

pathway_categories = {
    'oxygen_metabolism': [
        '2-aminophenol degradation',
        '4-hydroxyphenylacetate degradation',
        '4-methylcatechol degradation (ortho cleavage)',
        'CYCLOHEXANOL-OXIDATION-PWY',
        'PWY-5088',
        'PWY-6953',
        'PWY-7110',
        'PWY-7373',
        'aerobic respiration I (cytochrome c)',
        'benzoyl-CoA degradation I (aerobic)',
        'catalase',
        'catechol degradation I (meta-cleavage pathway)',
        'catechol degradation II (meta-cleavage pathway)',
        'catechol degradation III (ortho-cleavage pathway)',
        'catechol degradation to &beta;-ketoadipate',
        'catechol degradation to 2-oxopent-4-enoate II',
        'chlorophyllide a biosynthesis I (aerobic, light-dependent)',
        'chlorophyllide a biosynthesis III (aerobic, light independent)',
        'chlorosalicylate degradation',
        'cytochrome oxidase',
        'electrode respiration',
        'gallate degradation I',
        'gallate degradation II',
        'glucose degradation (oxidative)',
        'heme biosynthesis I (aerobic)',
        'meta cleavage pathway of aromatic compounds',
        'methylgallate degradation',
        'o2_consumption',
        'octane oxidation',
        'oxidase',
        'oxidative stress',
        'oxygen consumption',
        'oxygen reduction',
        'oxygen sensor',
        'oxygen tolerance',
        'oxygen-limited growth',
        'peroxidase',
        'phenylacetate degradation I (aerobic)',
        'photorespiration',
        'protocatechuate degradation I (meta-cleavage pathway)',
        'protocatechuate degradation II (ortho-cleavage pathway)',
        'reactive oxygen species',
        'solid-state respiration',
        'superoxide dismutase',
        'superpathway of aerobic toluene degradation',
        'superpathway of salicylate degradation',
        'syringate degradation',
        'terminal oxidase',
        'toluene degradation I (aerobic) (via o-cresol)',
        'toluene degradation II (aerobic) (via 4-methylcatechol)',
        'toluene degradation III (aerobic) (via p-cresol)',
        'toluene degradation IV (aerobic) (via catechol)',
        'vanillin and vanillate degradation I'
    ],
    'nitrogen_metabolism': [
        '2-amino-3-carboxymuconate semialdehyde degradation to 2-oxopentenoate',
        '2-nitrobenzoate degradation I',
        '4-aminobutanoate degradation V',
        '5-aminoimidazole ribonucleotide biosynthesis I',
        '5-aminoimidazole ribonucleotide biosynthesis II',
        '8-amino-7-oxonanoate biosynthesis I',
        'ADP-L-glycero-&beta;-D-manno-heptose biosynthesis',
        'ARGDEG-PWY',
        'ILEUDEG-PWY',
        'L-arginine biosynthesis I (via L-ornithine)',
        'L-arginine biosynthesis II (acetyl cycle)',
        'L-arginine biosynthesis III (via N-acetyl-L-citrulline)',
        'L-arginine biosynthesis IV (archaebacteria)',
        'L-arginine degradation II (AST pathway)',
        'L-glutamate and L-glutamine biosynthesis',
        'L-glutamate degradation V (via hydroxyglutarate)',
        'L-histidine biosynthesis',
        'L-histidine degradation I',
        'L-histidine degradation II',
        'L-isoleucine biosynthesis I (from threonine)',
        'L-isoleucine biosynthesis II',
        'L-isoleucine biosynthesis III',
        'L-isoleucine biosynthesis IV',
        'L-leucine degradation I',
        'L-lysine biosynthesis I',
        'L-lysine biosynthesis II',
        'L-lysine biosynthesis III',
        'L-lysine biosynthesis VI',
        'L-methionine biosynthesis III',
        'L-ornithine biosynthesis',
        'L-tryptophan biosynthesis',
        'L-tryptophan degradation IX',
        'L-tryptophan degradation XII (Geobacillus)',
        'L-tryptophan degradation to 2-amino-3-carboxymuconate semialdehyde',
        'L-tyrosine degradation I',
        'L-valine biosynthesis',
        'NAD biosynthesis II (from tryptophan)',
        'NAD salvage pathway I',
        'NAD salvage pathway II',
        'ORNARGDEG-PWY',
        'ORNDEG-PWY',
        'P163-PWY',
        'P3-PWY',
        'PWY-101',
        'PWY-1422',
        'PWY-5055',
        'PWY-5179',
        'PWY-5308',
        'PWY-5497',
        'PWY-5519',
        'PWY-6145',
        'PWY-6322',
        'PWY-6349',
        'PWY-6581',
        'PWY-6690',
        'PWY-6714',
        'PWY-6834',
        'PWY-6928',
        'PWY-6986',
        'PWY-7015',
        'PWY-7016',
        'PWY-7286',
        'PWY-7287',
        'PWY-7316',
        'PWY-7401',
        'PWY-7528',
        'PWY0-1338',
        'THREOCAT-PWY',
        'VALDEG-PWY',
        'adenine and adenosine salvage III',
        'adenosine deoxyribonucleotides de novo biosynthesis II',
        'adenosine nucleotides degradation II',
        'adenosine ribonucleotides de novo biosynthesis',
        'allantoin degradation IV (anaerobic)',
        'allantoin degradation to glyoxylate III',
        'ammonia oxidation',
        'ammonification',
        'anammox',
        'arginine, ornithine and proline interconversion',
        'aromatic biogenic amine degradation (bacteria)',
        'aspartate superpathway',
        'creatinine degradation I',
        'creatinine degradation II',
        'denitrification',
        'dissimilatory nitrate reduction',
        'ectoine biosynthesis',
        'ergothioneine biosynthesis I (bacteria)',
        'glycine betaine degradation I',
        'guanosine deoxyribonucleotides de novo biosynthesis II',
        'guanosine nucleotides degradation III',
        'guanosine ribonucleotides de novo biosynthesis',
        "inosine-5'-phosphate biosynthesis I",
        "inosine-5'-phosphate biosynthesis III",
        'nicotinate degradation I',
        'nitrate',
        'nitrate reduction',
        'nitrate reduction I (denitrification)',
        'nitrate reduction VI (assimilatory)',
        'nitrate respiration',
        'nitric oxide metabolism',
        'nitric oxide reduction',
        'nitrification',
        'nitrite',
        'nitrite reduction',
        'nitrite reductase',
        'nitrite respiration',
        'nitrogen fixation',
        'nitrogen metabolism',
        'norspermidine biosynthesis',
        'nitrous oxide reduction',
        'ppGpp biosynthesis',
        'preQ0 biosynthesis',
        'purine nucleobases degradation I (anaerobic)',
        'purine nucleotides degradation II (aerobic)',
        'purine ribonucleosides degradation',
        "pyridoxal 5'-phosphate biosynthesis I",
        'pyrimidine deoxyribonucleosides salvage',
        'pyrimidine deoxyribonucleotides biosynthesis from CTP',
        'pyrimidine deoxyribonucleotides de novo biosynthesis II',
        'pyrimidine deoxyribonucleotides de novo biosynthesis III',
        'pyrimidine deoxyribonucleotides de novo biosynthesis IV',
        'pyrimidine deoxyribonucleotides de novo biosynthesis I',
        'pyrimidine deoxyribonucleotide phosphorylation',
        'queuosine biosynthesis',
        'superpathway of L-isoleucine biosynthesis I',
        'superpathway of L-phenylalanine biosynthesis',
        'superpathway of L-threonine biosynthesis',
        'superpathway of L-tyrosine biosynthesis',
        'superpathway of alanine biosynthesis',
        'superpathway of arginine and polyamine biosynthesis',
        'superpathway of asparagine biosynthesis',
        'superpathway of histidine, purine, and pyrimidine biosynthesis',
        'superpathway of polyamine biosynthesis I',
        'superpathway of polyamine biosynthesis II',
        'superpathway of purine deoxyribonucleosides degradation',
        'superpathway of purine nucleotides de novo biosynthesis I',
        'superpathway of purine nucleotides de novo biosynthesis II',
        "superpathway of pyridoxal 5'-phosphate biosynthesis and salvage",
        'superpathway of pyrimidine deoxyribonucleoside salvage',
        'superpathway of pyrimidine deoxyribonucleosides degradation',
        'superpathway of pyrimidine nucleobases salvage',
        'superpathway of pyrimidine ribonucleosides salvage',
        'superpathway of thiamin diphosphate biosynthesis I',
        'superpathway of thiamin diphosphate biosynthesis II',
        'tRNA charging',
        'tRNA processing',
        'UMP biosynthesis',
        'urea cycle',
        "urate biosynthesis/inosine 5'-phosphate degradation"
    ],
    'iron_sulfur_redox': [
        'AEROBACTINSYN-PWY',
        'Fe-S cluster',
        'HEME-BIOSYNTHESIS-II',
        'P125-PWY',
        'PWY-6516',
        'PWY-7209',
        'PWY-7221',
        'S-adenosyl-L-methionine cycle I',
        'bacterioferritin',
        'enterobactin biosynthesis',
        'ferredoxin',
        'ferric reduc',
        'ferritin',
        'heme biosynthesis II (anaerobic)',
        'iron immobilization',
        'iron metabolism',
        'iron mobilization',
        'iron oxidation',
        'iron precipitation',
        'iron reduc',
        'iron reduction',
        'iron-sulfur cluster',
        'rubredoxin',
        'sulfate reduc',
        'sulfide',
        'sulfite',
        'sulfur metabolism',
        'sulfur oxidation',
        'superpathay of heme biosynthesis from glutamate',
        'superpathway of heme biosynthesis from glycine',
        'superpathway of heme biosynthesis from uroporphyrinogen-III',
        'tetrapyrrole biosynthesis I (from glutamate)',
        'tetrapyrrole biosynthesis II (from glycine)',
        'thiosulfate'
    ],
    'ocre_formation': [
        'PWY-7219',
        'biogenic iron oxides',
        'ferrihydrite',
        'goethite',
        'hematite',
        'iron mineral',
        'iron oxide deposits',
        'iron_deposit',
        'iron_oxide',
        'magnetite',
        'metal oxide',
        'mineral precipitation',
        'ochre formation',
        'ochre mats',
        'ocre',
        'rust formation',
        'stalactite formation'
    ],
    'manganese_processes': [
        'Mn-oxide formation',
        'Mn-oxide reduction',
        'Mn precipitation',
        'Mn dissolution',
        'birnessite',
        'manganese cycling',
        'manganese mineral',
        'manganese oxidation',
        'manganese oxide',
        'manganese transport',
        'manganese_reduction',
        'mn_redox',
        'pyrolusite'
    ],
    'sulfur_metabolism': [
        'APS reductase',
        'L-methionine biosynthesis I',
        'L-methionine salvage cycle III',
        'PWY-5327',
        'PWY-5392',
        'PWY-6932',
        'PWY-6937',
        'S-methyl-5-thio-&alpha;-D-ribose 1-phosphate degradation',
        'SO4ASSIM-PWY',
        'SRB',
        'SULFATE-CYS-PWY',
        'coenzyme M biosynthesis I',
        'dissimilatory sulfate reduction',
        'dsrAB',
        'elemental sulfur',
        'mycothiol biosynthesis',
        'polysulfide metabolism',
        'sulfate',
        'sulfate reduction',

        'sulfate reduction I (assimilatory)',
        'sulfide',
        'sulfide:quinone oxidoreductase',
        'sulfite',
        'sulfoglycolysis',
        'sulfonate',
        'sulfur',
        'sulfur disproportionation',
        'sulfur globules',
        'sulfur granules',
        'sulfur oxidation',
        'sulfur respiration',
        'superpathway of L-methionine biosynthesis (by sulfhydrylation)',
        'superpathway of L-methionine biosynthesis (transsulfuration)',
        'superpathway of S-adenosyl-L-methionine biosynthesis',
        'superpathway of sulfate assimilation and cysteine biosynthesis',
        'superpathway of sulfolactate degradation',
        'superpathway of sulfur oxidation (Acidianus ambivalens)',
        'superpathway of taurine degradation',
        'thiosulfate'
    ],
    'hydrogen_metabolism': [
        'H2 sensing',
        'H2ase',
        'FeFe-hydrogenase',
        'H2 oxidation',
        'NiFe-hydrogenase',
        'h2',
        'h2_consumption',
        'hydrogen consumption',
        'hydrogen cycling',
        'hydrogen evolution',
        'hydrogen production',
        'hydrogen uptake',
        'hydrogenase',
        'proton reduction'
    ],
    'organic_acid_metabolism': [
        '(5Z)-dodec-5-enoate biosynthesis',
        '2-methylcitrate cycle I',
        '2-methylcitrate cycle II',
        '3-phenylpropanoate degradation',
        'CENTFERM-PWY',
        'FERMENTATION-PWY',
        'GALACTUROCAT-PWY',
        'GLYCOLYSIS',
        'METHGLYUT-PWY',
        'PWY-5100',
        'PWY-5751',
        'PWY-5757',
        'PROPFERM-PWY',
        'acetate',
        'acetate metabolism',
        'acetate production',
        'acetic acid',
        'acetyl',
        'acetyl-CoA fermentation to butanoate II',
        'butyrate',
        'butyric acid',
        'caproic acid',
        'carboxylic acid',
        'cis-vaccenate biosynthesis',
        'citrate',
        'citric acid',
        'fatty acid',
        'fatty acid &beta;-oxidation I',
        'fatty acid elongation',
        'fatty acid elongation -- saturated',
        'fatty acid salvage',
        'formate',
        'formic acid',
        'fumarate',
        'fumaric acid',
        'gluconic acid',
        'gondoate biosynthesis (anaerobic)',
        'heterolactic fermentation',
        'hexitol fermentation to lactate, formate, ethanol and acetate',
        'homolactic fermentation',
        'isopropanol biosynthesis',
        'lactate',
        'lactic acid',
        'malate',
        'malic acid',
        'methyl ketone biosynthesis',
        'mixed acid fermentation',
        'mycolate biosynthesis',
        'oleate biosynthesis IV (anaerobic)',
        'organic acid',
        'oxalate',
        'oxalate metabolism',
        'oxalate production',
        'oxalic acid',
        'palmitate biosynthesis II (bacteria and plants)',
        'palmitoleate biosynthesis I (from (5Z)-dodec-5-enoate)',
        'propionate',
        'propionic acid',
        'pyruvate',
        'pyruvate fermentation to acetate and lactate II',
        'pyruvate fermentation to acetone',
        'pyruvate fermentation to butanoate',
        'pyruvate fermentation to propanoate I',
        'pyruvic acid',
        'stearate biosynthesis II (bacteria and plants)',
        'succinate',
        'succinic acid',
        'superpathway of (R,R)-butanediol biosynthesis',
        'superpathway of 2,3-butanediol biosynthesis',
        'superpathway of Clostridium acetobutylicum acidogenic fermentation',
        'tartaric acid',
        'valeric acid'
    ],
    'metal_organic_interaction': [
        '6-hydroxymethyl-dihydropterin diphosphate biosynthesis I',
        '6-hydroxymethyl-dihydropterin diphosphate biosynthesis III (Chlamydia)',
        'P181-PWY',
        'P341-PWY',
        'PHOTOALL-PWY',
        'adenosylcobalamin biosynthesis I (early cobalt insertion)',
        'adenosylcobalamin biosynthesis II (late cobalt incorporation)',
        'adenosylcobalamin biosynthesis from cobyrinate a,c-diamide I',
        'adenosylcobalamin salvage from cobinamide I',
        'adenosylcobalamin salvage from cobinamide II',
        'biotin biosynthesis I',
        'biotin biosynthesis II',
        'chelator secretion',
        'cob(II)yrinate a,c-diamide biosynthesis I (early cobalt insertion)',
        'cob(II)yrinate a,c-diamide biosynthesis II (late cobalt incorporation)',
        'ferric reductase',
        'ferrous oxidase',
        'iron chelation',
        'iron complex',
        'iron uptake',
        'iron-sulfur cluster',
        'metal bioavailability',
        'metal binding',
        'metal chelation',
        'metal coordination',
        'metal homeostasis',
        'metal organic',
        'metal sequestration',
        'metal transport',
        'metal uptake',
        'metal-ligand complex',
        'metallophore',
        'metallophore production',
        'metalloprotein',
        'organometallic',
        'siderophore',
        'superpathway of bacteriochlorophyll a biosynthesis',
        'superpathway of tetrahydrofolate biosynthesis',
        'superpathway of tetrahydrofolate biosynthesis and salvage',
        'thiazole biosynthesis I (E. coli)',
        'thiazole biosynthesis II (Bacillus)'
    ],
    'biofilm_formation': [
        'CDP-diacylglycerol biosynthesis I',
        'CDP-diacylglycerol biosynthesis II',
        'CMP-3-deoxy-D-manno-octulosonate biosynthesis I',
        'CMP-legionaminate biosynthesis I',
        'COLANSYN-PWY',
        'ECASYN-PWY',
        'EXOPOLYSACC-PWY',
        'GDP-D-glycero-&alpha;-D-manno-heptose biosynthesis',
        'GDP-mannose biosynthesis',
        'GLUCOSE1PMETAB-PWY',
        'Kdo transfer to lipid IVA III (Chlamydia)',
        'LIPASYN-PWY',
        'LPSSYN-PWY',
        'O-antigen building blocks biosynthesis (E. coli)',
        'UDP-2,3-diacetamido-2,3-dideoxy-&alpha;-D-mannuronate biosynthesis',
        'UDP-N-acetyl-D-glucosamine biosynthesis I',
        'UDP-N-acetylmuramoyl-pentapeptide biosynthesis I (meso-diaminopimelate containing)',
        'UDP-N-acetylmuramoyl-pentapeptide biosynthesis II (lysine-containing)',
        'adhesion',
        'alginate synthesis',
        'amyloid fiber',
        'anhydromuropeptides recycling',
        'attachment',
        'bioelectricity',
        'biofilm',
        'biofilm architecture',
        'cell aggregation',
        'cell-cell adhesion',
        'cellulose biosynthesis',
        'colanic acid building blocks biosynthesis',
        'colonization',
        'dTDP-N-acetylthomosamine biosynthesis',
        'exopolysaccharide',
        'extracellular matrix',
        'extracellular polymeric substance',
        'floc formation',
        'lipid IVA biosynthesis',
        'matrix production',
        'mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
        'pellicle',
        'peptidoglycan biosynthesis I (meso-diaminopimelate containing)',
        'peptidoglycan biosynthesis II (staphylococci)',
        'peptidoglycan biosynthesis III (mycobacteria)',
        'peptidoglycan biosynthesis IV (Enterococcus faecium)',
        'peptidoglycan biosynthesis V (&beta;-lactam resistance)',
        'peptidoglycan maturation (meso-diaminopimelate containing)',
        'phosphatidylglycerol biosynthesis I (plastidic)',
        'phosphatidylglycerol biosynthesis II (non-plastidic)',
        'polysaccharide biosynthesis',
        'quorum sensing',
        'superpathway of (Kdo)2-lipid A biosynthesis',
        'superpathway of GDP-mannose-derived O-antigen building blocks biosynthesis',
        'superpathway of N-acetylglucosamine, N-acetylmannosamine and N-acetylneuraminate degradation',
        'superpathway of N-acetylneuraminate degradation',
        'superpathway of UDP-N-acetylglucosamine-derived O-antigen building blocks biosynthesis',
        'superpathway of UDP-glucose-derived O-antigen building blocks biosynthesis',
        'superpathway of fatty acid biosynthesis initiation (E. coli)',
        'superpathway of mycolyl-arabinogalactan-peptidoglycan complex biosynthesis',
        'superpathway of phospholipid biosynthesis I (bacteria)',
        'surface attachment',
        'teichoic acid (poly-glycerol) biosynthesis'
    ],
    'carbon_metabolism': [
        '1,4-dihydroxy-2-naphthoate biosynthesis I',
        '1,4-dihydroxy-6-naphthoate biosynthesis I',
        '1,4-dihydroxy-6-naphthalene carboxylate biosynthesis',
        '3-hydroxypropanoate cycle',
        '4-coumarate degradation (anaerobic)',
        '4-deoxy-L-threo-hex-4-enopyranuronate degradation',
        'BENZCOA-PWY',
        'Bifidobacterium shunt',
        'Calvin cycle',
        'Calvin-Benson-Bassham cycle',
        'CAROTENOID-PWY',
        'D-fructuronate degradation',
        'D-galactarate degradation I',
        'D-galacturonate degradation I',
        'D-glucarate degradation I',
        'GLUDEG-II-PWY',
        'HCAMHPDEG-PWY',
        'L-1,2-propanediol degradation',
        'L-arabinose degradation IV',
        'L-rhamnose degradation I',
        'NPGLUCAT-PWY',
        'P241-PWY',
        'PWY-1622',
        'PWY-1882',
        'PWY-2201',
        'PWY-2221',
        'PWY-2504',
        'PWY-3081',
        'PWY-3801',
        'PWY-3941',
        'PWY-5062',
        'PWY-5184',
        'PWY-5257',
        'PWY-5266',
        'PWY-5273',
        'PWY-5280',
        'PWY-5283',
        'PWY-5306',
        'PWY-5488',
        'PWY-5634',
        'PWY-5656',
        'PWY-5675',
        'PWY-5677',
        'PWY-5724',
        'PWY-5737',
        'PWY-5789',
        'PWY-5823',
        'PWY-5940',
        'PWY-6060',
        'PWY-6113',
        'PWY-6141',
        'PWY-6142',
        'PWY-6143',
        'PWY-6146',
        'PWY-6148',
        'PWY-6165',
        'PWY-6167',
        'PWY-6215',
        'PWY-622',
        'PWY-6281',
        'PWY-6284',
        'PWY-6285',
        'PWY-6324',
        'PWY-6344',
        'PWY-6350',
        'PWY-6374',
        'PWY-6395',
        'PWY-6486',
        'PWY-6538',
        'PWY-6565',
        'PWY-6572',
        'PWY-6583',
        'PWY-6594',
        'PWY-6604',
        'PWY-6629',
        'PWY-6632',
        'PWY-6654',
        'PWY-6655',
        'PWY-6660',
        'PWY-6662',
        'PWY-6676',
        'PWY-6682',
        'PWY-6713',
        'PWY-6728',
        'PWY-6748',
        'PWY-6760',
        'PWY-6785',
        'PWY-6797',
        'PWY-6823',
        'PWY-6830',
        'PWY-6863',
        'PWY-6883',
        'PWY-6886',
        'PWY-6942',
        'PWY-6945',
        'PWY-6946',
        'PWY-6947',
        'PWY-6954',
        'PWY-6956',
        'PWY-6961',
        'PWY-6962',
        'PWY-6977',
        'PWY-6992',
        'PWY-6993',
        'PWY-6999',
        'PWY-7000',
        'PWY-7002',
        'PWY-7020',
        'PWY-7021',
        'PWY-7044',
        'PWY-7084',
        'PWY-7102',
        'PWY-7124',
        'PWY-7128',
        'PWY-7153',
        'PWY-7165',
        'PWY-7185',
        'PWY-7218',
        'PWY-7224',
        'PWY-7274',
        'PWY-7290',
        'PWY-7294',
        'PWY-7312',
        'PWY-7317',
        'PWY-7318',
        'PWY-7385',
        'PWY-7398',
        'PWY-7399',
        'PWY-7402',
        'PWY-7413',
        'PWY-7414',
        'PWY-7483',
        'PWY-7524',
        'PWY-7575',
        'PWY-7596',
        'PWY-7626',
        'PWY-822',
        'PWY0-1277',
        'TCA cycle',
        'TCA cycle IV (2-oxoglutarate decarboxylase)',
        'TCA cycle V (2-oxoglutarate:ferredoxin oxidoreductase)',
        'TCA cycle VI (obligate autotrophs)',
        'TCA cycle VII (acetate-producers)',
        'TCA cycle VIII (helicobacter)',
        'acetylene degradation',
        'androstenedione degradation',
        'aromatic compounds degradation via &beta;-ketoadipate',
        'carbon assimilation',
        'carbon catabolite repression',
        'carbon fixation',
        'carbon monoxide dehydrogenase',
        'carbon storage',
        'carbon utilization',
        'carbohydrate metabolism',
        'chitin derivatives degradation',
        'chorismate biosynthesis I',
        'chorismate biosynthesis from 3-dehydroquinate',
        'coenzyme A biosynthesis I',
        'ethylmalonyl-CoA pathway',
        'flavin biosynthesis I (bacteria and plants)',
        'formaldehyde assimilation II (RuMP Cycle)',
        'formaldehyde oxidation I',
        'fucose degradation',
        'galactose degradation I (Leloir pathway)',
        'gluconeogenesis',
        'gluconeogenesis I',
        'glucose and glucose-1-phosphate degradation',
        'glutaryl-CoA degradation',
        'glycogen metabolism',
        'glycolysis',
        'glycolysis I (from glucose 6-phosphate)',
        'glycolysis II (from fructose 6-phosphate)',
        'glycolysis III (from glucose)',
        'glyoxylate assimilation',
        'glyoxylate cycle',
        'isoprene biosynthesis II (engineered)',
        'ketogluconate metabolism',
        'lactose and galactose degradation I',
        'mandelate degradation I',
        'mandelate degradation to acetyl-CoA',
        'mannan degradation',
        'methanol oxidation to carbon dioxide',
        'methylphosphonate degradation I',
        'methylerythritol phosphate pathway I',
        'methylerythritol phosphate pathway II',
        'mevalonate pathway I',
        'mevalonate pathway II (archaea)',
        'mono-trans, poly-cis decaprenyl phosphate biosynthesis',
        'myo-, chiro- and scillo-inositol degradation',
        'myo-inositol degradation I',
        'nylon-6 oligomer degradation',
        'pantothenate and coenzyme A biosynthesis I',
        'pentose phosphate pathway',
        'pentose phosphate pathway (non-oxidative branch)',
        'phenylacetate degradation I (aerobic)',
        'phosphopantothenate biosynthesis I',
        'polyisoprenoid biosynthesis (E. coli)',
        'pyruvate fermentation to isobutanol (engineered)',
        'reductive acetyl coenzyme A pathway',
        'sitosterol degradation to androstenedione',
        'starch degradation III',
        'starch degradation V',
        'sucrose biosynthesis I (from photosynthesis)',
        'sucrose biosynthesis III',
        'sucrose degradation III (sucrose invertase)',
        'sucrose degradation IV (sucrose phosphorylase)',
        'superpathway of &beta;-D-glucuronide and D-glucuronate degradation',
        'superpathway of D-glucarate and D-galactarate degradation',
        'superpathway of adenosine nucleotides de novo biosynthesis I',
        'superpathway of adenosine nucleotides de novo biosynthesis II',
        'superpathway of aromatic amino acid biosynthesis',
        'superpathway of branched amino acid biosynthesis',
        'superpathway of chorismate metabolism',
        'superpathway of demethylmenaquinol-6 biosynthesis I',
        'superpathway of demethylmenaquinol-8 biosynthesis',
        'superpathway of demethylmenaquinol-9 biosynthesis',
        'superpathway of fucose and rhamnose degradation',
        'superpathway of geranylgeranyl diphosphate biosynthesis II (via MEP)',
        'superpathway of geranylgeranyldiphosphate biosynthesis I (via mevalonate)',
        'superpathway of glucose and xylose degradation',
        'superpathway of glycerol degradation to 1,3-propanediol',
        'superpathway of glycol metabolism and degradation',
        'superpathway of glycolysis and Entner-Doudoroff',
        'superpathway of glycolysis, pyruvate dehydrogenase, TCA, and glyoxylate bypass',
        'superpathway of guanosine nucleotides de novo biosynthesis I',
        'superpathway of guanosine nucleotides de novo biosynthesis II',
        'superpathway of hexitol degradation (bacteria)',
        'superpathway of hexuronide and hexuronate degradation',
        'superpathway of menaquinol-10 biosynthesis',
        'superpathway of menaquinol-11 biosynthesis',
        'superpathway of menaquinol-12 biosynthesis',
        'superpathway of menaquinol-13 biosynthesis',
        'superpathway of menaquinol-6 biosynthesis I',
        'superpathway of menaquinol-7 biosynthesis',
        'superpathway of menaquinol-8 biosynthesis I',
        'superpathway of menaquinol-8 biosynthesis II',
        'superpathway of menaquinol-9 biosynthesis',
        'superpathway of phenylethylamine degradation',
        'superpathway of phylloquinol biosynthesis',
        'superpathway of the 3-hydroxypropanoate cycle',
        'superpathway of ubiquinol-8 biosynthesis (prokaryotic)',
        'superpathway of vanillin and vanillate degradation',
        'taxadiene biosynthesis (engineered)',
        'thiamin salvage II',
        'vanillin and vanillate degradation II'
    ],
    'methanogenesis': [
        'METHANOGENESIS-PWY',
        'CO2 reduction',
        'acetoclastic methanogenesis',
        'archaea',
        'coenzyme F420',
        'hydrogenotrophic methanogenesis',
        'methane production',
        'methanobacterium',
        'methanogenesis',
        'methanogenesis from acetate',
        'methanogenic',
        'methanotrophy',
        'methyl-coenzyme M reductase',
        'methyl-H4MPT',
        'methylotrophic methanogenesis'
    ],
    'phosphorus_metabolism': [
        'NAD salvage pathway I',
        'NAD salvage pathway II',
        'adenosine ribonucleotides de novo biosynthesis',
        'guanosine ribonucleotides de novo biosynthesis',
        'methylphosphonate degradation I',
        'phosphate precipitation',
        'phosphate solubilization',
        'phosphate transport',
        'phosphate uptake',
        'phosphorus cycling',
        'polyphosphate',
        'struvite formation',
        'superpathway of pyrimidine deoxyribonucleotides de novo biosynthesis',
        'superpathway of pyrimidine nucleobases salvage',
        'superpathway of pyrimidine ribonucleotides de novo biosynthesis'
    ]
}

#7 Environmental factors/ Operational Factors
Environmental_factors = {
'halogen_related': ['halogen', 'chloride', 'bromide', 'iodide', 'fluoride', 'halide', 'dehalogenation', 'haloperoxidase', 'haloacid', 'chlorination', 'bromination', 'organohalide', 'halomethane', 'haloalkane', 'organohalide', 'halotolerance', 'salt tolerance', 'halophilic', 'chloride transport', 'halide channel', 'chloride attack', 'chloride-induced corrosion', 'pitting initiation', 'chloride penetration', 'halide corrosion', 'perchlorate reduction', 'halorespiration', 'organohalide'],
'microaerobic_conditions': ['microaerophilic', 'oxygen-limited', 'hypoxic', 'microaerobic'],
'ph_modulation': ['acid tolerance', 'alkaline tolerance', 'proton pump', 'pH homeostasis', 'pH stress', 'pH regulation', 'acid resistance', 'pH buffering', 'pH gradient', 'acidophile', 'alkaliphile'], 
'direct_eet': ['electron transfer', 'extracellular electron transfer', 'direct electron transfer',  'solid-state respiration', 'interfacial electron transfer', 'electrode respiration', 'bioelectricity', 'electron shuttle', 'electron bridge','electron conduit', 'oxidoreductase', 'reductase', 'oxidase', 'redox',  'cytochrome', 'c-type cytochrome', 'multi-heme cytochrome', 'cytochrome c oxidase',  'quinol oxidase', 'NADH:quinone oxidoreductase', 'succinate dehydrogenase',  'fumarate reductase', 'mtrABC', 'omc', 'omcS', 'nanowire', 'microbial nanowires',  'conductive pili', 'type IV pili', 'conductive biofilms', 'flavin',  'riboflavin shuttle', 'flavin secretion', 'histidine kinase', 'PROTEIN-KINASE-RXN',  'L-arginine biosynthesis II', 'chorismate biosynthesis I',  'superpathway of branched amino acid biosynthesis',  'superpathway of aromatic amino acid biosynthesis',  'L-lysine biosynthesis I', 'L-ornithine biosynthesis', 'oxidoreductase activity'],
'indirect_eet': ['shuttle', 'mediator', 'redox mediator', 'electron shuttle', 'flavin', 'quinone', 'humic substance', 'pyocyanin', 'phenazine', 'riboflavin'], 
'exoelectrogenesis': ['exoelectrogen', 'electrochemically active bacteria', 'EAB', 'extracellular respiration', 'electrode respiration', 'bioelectrosynthesis', 'microbial fuel cell'], 
'enzymatic_corrosion': ['enzyme-mediated corrosion', 'metalloenzyme', 'enzyme-catalyzed oxidation', 'enzyme-catalyzed reduction', 'peroxidase', 'laccase', 'oxidoreductase activity'], 
'dealloying': ['selective corrosion', 'dezincification', 'dealuminification', 'parting', 'selective leaching', 'alloy corrosion', 'preferential dissolution'], 
'galvanic_corrosion': ['bimetallic corrosion', 'galvanic couple', 'differential aeration', 'local cell formation', 'microelectrochemical cells', 'electrolytic corrosion'], 
'chloride_attack': ['chloride-induced corrosion', 'pitting initiation', 'localized corrosion', 'crevice corrosion', 'stress corrosion cracking', 'chloride penetration'], 
'microbe_metal_synergy': ['metal-microbe interaction', 'biomineralization', 'biosorption', 'bioaccumulation', 'metal-binding proteins', 'metallothionein', 'metal-enzyme complex'], 
'cathodic_depolarization': ['cathodic depolarization', 'hydrogen depolarization', 'cathodic reaction enhancement', 'electron acceptor consumption', 'cathodic process acceleration'],
'passivity_breakdown': ['passivation breakdown', 'passive film disruption', 'oxide layer dissolution', 'passive layer damage', 'depassivation'],
'concentration_cells': ['concentration cell', 'differential concentration', 'ion concentration gradient', 'oxygen concentration cell', 'metal ion gradient'],
'syntrophic_interactions': ['syntrophic', 'cross-feeding', 'metabolic coupling', 'interspecies', 'consortia', 'metabolic cooperation']
} 
  